/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2018-04-03 03:56:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.vrBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vrBoard.model.vo.*;
import java.util.*;
import likePlace.model.vo.likePlace;
import member.model.vo.Member;

public final class vrBoardSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/vrBoard/../../footer.jsp", Long.valueOf(1517555554000L));
    _jspx_dependants.put("/views/vrBoard/../../header.jsp", Long.valueOf(1518076440000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("vrBoard.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("likePlace.model.vo.likePlace");
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
vrBoard board = (vrBoard)request.getAttribute("board");
ArrayList<vrBoard> listAll = (ArrayList<vrBoard>) request.getAttribute("listAll");
String placeName = (String)request.getAttribute("place");
ArrayList<likePlace> like = (ArrayList<likePlace>)request.getAttribute("like");
Maplocation maplocation = (Maplocation) request.getAttribute("maplo");
VrBoardDetail vbd =(VrBoardDetail) request.getAttribute("vbd");
ArrayList<vrBoard> resBoard = (ArrayList<vrBoard>)request.getAttribute("resBoard");
ArrayList<DetailComment> list2 = (ArrayList<DetailComment>)request.getAttribute("list2"); 
ArrayList<VrBoardDetail> resBoardDetail = (ArrayList<VrBoardDetail>)request.getAttribute("resBoardDetail");

int resCount=0;
int bnum=0;
int count=0;
boolean flag=false;
boolean f = false;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Place</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("   src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"css/1-col-portfolio.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("@import url(//fonts.googleapis.com/earlyaccess/nanumpenscript.css);\r\n");
      out.write("div.mainmain1{\r\n");
      out.write("   float:left; width:15%;\r\n");
      out.write("}\r\n");
      out.write("div.mainmain2{\r\n");
      out.write("   float:left; width:55%;\r\n");
      out.write("   align : center;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".modal-size {\r\n");
      out.write("   width:750px;\r\n");
      out.write("   height: 450px;\r\n");
      out.write("}\r\n");
      out.write(".n5{font-family: 'Nanum Pen Script', cursive; font-size:25px;}\r\n");
      out.write("\r\n");
      out.write("div.coll{\r\n");
      out.write("   width : 100%;\r\n");
      out.write("   align : center;\r\n");
      out.write("}\r\n");
      out.write(" .n4{ font-family: 'Nanum Pen Script', cursive; font-size:25px; }\r\n");
      out.write("div.floating{\r\n");
      out.write("position:fixed;\r\n");
      out.write("right:50%;\r\n");
      out.write("top:120px;\r\n");
      out.write("margin-right:-850px;\r\n");
      out.write("float:left; \r\n");
      out.write("/* margine : 0 auto; */\r\n");
      out.write("width:15%;\r\n");
      out.write("/* background : lightgray; */\r\n");
      out.write("border : 1px solid lightgray;\r\n");
      out.write("border-radius: 2em;\r\n");
      out.write("background : white;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("div.infloating{\r\n");
      out.write("   background : lightgray;\r\n");
      out.write("border-top-left-radius: 2em;\r\n");
      out.write("border-top-right-radius: 2em;\r\n");
      out.write("}\r\n");
      out.write("div.ininfloat{\r\n");
      out.write(" background : white;\r\n");
      out.write("border-bottom-left-radius: 2em;\r\n");
      out.write("border-bottom-right-radius: 2em;\r\n");
      out.write(" border : 1px solid lightgray;\r\n");
      out.write("}\r\n");
      out.write("div.mainmain3{\r\n");
      out.write("   float:left; \r\n");
      out.write("   width:30%;\r\n");
      out.write("   \r\n");
      out.write("   margine : 0 auto;\r\n");
      out.write("}\r\n");
      out.write("      h1 { font-family: 'Nanum Pen Script', cursive; }\r\n");
      out.write("      .npps { font-family: 'Nanum Pen Script', cursive; font-size:30px; }\r\n");
      out.write("      h3 { font-family: 'Nanum Pen Script', cursive; font-size:45px;  }\r\n");
      out.write("        .npps2 { font-family: 'Nanum Pen Script', cursive; font-size:30px; }\r\n");
      out.write("         .n3 { font-family: 'Nanum Pen Script', cursive; font-size:30px; }\r\n");
      out.write(" div.insta-back{\r\n");
      out.write("background:white;\r\n");
      out.write("width : 800px;\r\n");
      out.write("height : 500px;\r\n");
      out.write("position : fixed;\r\n");
      out.write("margin-left : -200px;\r\n");
      out.write("margin-top: +150px;\r\n");
      out.write("}\r\n");
      out.write("div.insta{\r\n");
      out.write("/* display:inline; */\r\n");
      out.write("background:white;\r\n");
      out.write("width : 800px;\r\n");
      out.write("height : 500px;\r\n");
      out.write("}\r\n");
      out.write("div.insta.ga{\r\n");
      out.write("float:left;\r\n");
      out.write("width:60%;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("div.insta.se{\r\n");
      out.write("float:left;\r\n");
      out.write("width:40%;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("div.insta.se.up{\r\n");
      out.write("height:50%;\r\n");
      out.write("}\r\n");
      out.write("div.down{\r\n");
      out.write("width:50%;\r\n");
      out.write("}\r\n");
      out.write(".res{\r\n");
      out.write("   margin:0 auto;\r\n");
      out.write("}\r\n");
      out.write(" table.type031 {\r\n");
      out.write("   border-collapse: collapse;\r\n");
      out.write("   text-align: left;\r\n");
      out.write("   line-height: 1.5;\r\n");
      out.write("   /* border-top: 1px solid #ccc; */\r\n");
      out.write("   border-left: 3px solid gray;\r\n");
      out.write("   margin-left:10px;\r\n");
      out.write("   font-family: 'Nanum Pen Script';\r\n");
      out.write("   \r\n");
      out.write("   width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.type031 th {\r\n");
      out.write("   width: 147px;\r\n");
      out.write("   padding: 10px;\r\n");
      out.write("   \r\n");
      out.write("   vertical-align: top;\r\n");
      out.write("   font-family: 'Nanum Pen Script';\r\n");
      out.write("   font-size:25px;\r\n");
      out.write("  /*  border-right: 8px solid #343A40;\r\n");
      out.write("    border-bottom: 1px solid #ccc;  */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.type031 td {\r\n");
      out.write("   width: 349px;\r\n");
      out.write("   padding: 10px;\r\n");
      out.write("   vertical-align: top;\r\n");
      out.write("   /* border-right: 1px solid #ccc;\r\n");
      out.write("   border-bottom: 1px solid #ccc; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("dl {\r\n");
      out.write("   width: 200px;\r\n");
      out.write("   left : 20px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dt {\r\n");
      out.write("   line-height: 35px;\r\n");
      out.write("   font-size: 18pt;\r\n");
      out.write("   text-indent: 3em;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   color: black;\r\n");
      out.write("   height: 40px;\r\n");
      out.write("   border-bottom: 1px solid gray;\r\n");
      out.write("   border-top: 1px solid gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dt.over {\r\n");
      out.write("   background-color:#eee;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   color:black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dt.selected {\r\n");
      out.write("    background-color:#343A40;\r\n");
      out.write("   cursor: default;\r\n");
      out.write("   color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dd {\r\n");
      out.write("   height: 300px;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#map {\r\n");
      out.write("   height: 300px;\r\n");
      out.write("   width:70%;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("   color:black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.homepage{\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("   color:#888;\r\n");
      out.write("   font-size:25px;\r\n");
      out.write("}\r\n");
      out.write("/* .resimg:hover{\r\n");
      out.write("   -webkit-transform: scale(1.2);\r\n");
      out.write("   transition: all 0.3s ease-in-out; \r\n");
      out.write("   opacity:0.5;\r\n");
      out.write("   filter:alpha(opacity=80);\r\n");
      out.write("}  */\r\n");
      out.write("figure.snip1141 {\r\n");
      out.write("\r\n");
      out.write("   position: relative;\r\n");
      out.write("  float: left; \r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  margin: 10px 1%; \r\n");
      out.write("  min-width: 250px;\r\n");
      out.write("  max-width: 250px;\r\n");
      out.write("  max-height: 250px; \r\n");
      out.write("  min-height: 250px;\r\n");
      out.write("  /* width: 100%; */\r\n");
      out.write("  background: #000000;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141 * {\r\n");
      out.write("  -webkit-box-sizing: border-box;\r\n");
      out.write("  box-sizing: border-box; \r\n");
      out.write("  -webkit-transition: all 0.4s ease-in-out;\r\n");
      out.write("  transition: all 0.4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141 img {\r\n");
      out.write("  /* max-width: 100%; */\r\n");
      out.write("  /* position: relative; */\r\n");
      out.write("  opacity: 0.9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141 .circle {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  height: 55px;\r\n");
      out.write("  width: 55px;\r\n");
      out.write("  top: 0%;\r\n");
      out.write("  left: 0%;\r\n");
      out.write("  background-color: rgba(0, 0, 0, 0.4);\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141 .circle:before,\r\n");
      out.write("figure.snip1141 .circle:after {\r\n");
      out.write("  border: 2px solid white;\r\n");
      out.write("  border-right-color: transparent;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  content: '';\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  -webkit-box-sizing: border-box;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  -webkit-transition: all 0.35s ease-in-out;\r\n");
      out.write("  transition: all 0.35s ease-in-out;\r\n");
      out.write("  -webkit-transition-delay: 0.3s;\r\n");
      out.write("  transition-delay: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141 .circle:before {\r\n");
      out.write("  -webkit-transform: rotate(45deg);\r\n");
      out.write("  transform: rotate(45deg);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141 .circle:after {\r\n");
      out.write("  -webkit-transform: rotate(-45deg);\r\n");
      out.write("  transform: rotate(-45deg);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141 figcaption {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 20px;\r\n");
      out.write("  left: 20px;\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141 h3 {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  font-weight: 300;\r\n");
      out.write("  letter-spacing: -1px;\r\n");
      out.write("  line-height: 55px;\r\n");
      out.write("  top: 0%;\r\n");
      out.write("  left: 0%;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 0 20px;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  -webkit-transform: translateX(-10%);\r\n");
      out.write("  transform: translateX(-10%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141 .icon {\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141 i {\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-size: 48px;\r\n");
      out.write("  line-height: 55px;\r\n");
      out.write("  -webkit-transition-delay: 0.3s;\r\n");
      out.write("  transition-delay: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141 a {\r\n");
      out.write("  left: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141:hover .circle,\r\n");
      out.write("figure.snip1141.hover .circle {\r\n");
      out.write("  background-color: rgba(0, 0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141:hover .circle:before,\r\n");
      out.write("figure.snip1141.hover .circle:before,\r\n");
      out.write("figure.snip1141:hover .circle:after,\r\n");
      out.write("figure.snip1141.hover .circle:after {\r\n");
      out.write("  -webkit-transform: rotate(0deg);\r\n");
      out.write("  transform: rotate(0deg);\r\n");
      out.write("  -webkit-transition-delay: 0s;\r\n");
      out.write("  transition-delay: 0s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141:hover h3,\r\n");
      out.write("figure.snip1141.hover h3 {\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("  -webkit-transition-delay: 0.3s;\r\n");
      out.write("  transition-delay: 0.3s;\r\n");
      out.write("  -webkit-transform: translateX(0);\r\n");
      out.write("  transform: translateX(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141:hover img,\r\n");
      out.write("figure.snip1141.hover img {\r\n");
      out.write("  opacity: 0.35;\r\n");
      out.write("  -webkit-transform: scale(1.1);\r\n");
      out.write("  transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure.snip1141:hover i,\r\n");
      out.write("figure.snip1141.hover i {\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  -webkit-transition-delay: 0s;\r\n");
      out.write("  transition-delay: 0s;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("    $(window).scroll(function() {\r\n");
      out.write("        if ($(this).scrollTop() > 300) {\r\n");
      out.write("            $('#MOVE_TOP_BTN').fadeIn();\r\n");
      out.write("        } else {\r\n");
      out.write("            $('#MOVE_TOP_BTN').fadeOut();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\"#MOVE_TOP_BTN\").click(function() {\r\n");
      out.write("        $('html, body').animate({\r\n");
      out.write("            scrollTop : 0\r\n");
      out.write("        }, 400);\r\n");
      out.write("        return false;\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   $(function() {\r\n");
      out.write("      $(\"dd:not(:first)\").css(\"display\", \"none\");\r\n");
      out.write("      $(\"dt:first\").addClass(\"selected\");\r\n");
      out.write("      $(\"dl dt\").click(function() {\r\n");
      out.write("         if ($(\"+dd\", this).css(\"display\") == \"none\") {\r\n");
      out.write("            $(\"dd\").slideUp(\"slow\");\r\n");
      out.write("            $(\"+dd\", this).slideDown(\"slow\");\r\n");
      out.write("            $(\"dt\").removeClass(\"selected\");\r\n");
      out.write("            $(this).addClass(\"selected\");\r\n");
      out.write("         }\r\n");
      out.write("      }).mouseover(function() {\r\n");
      out.write("         $(this).addClass(\"over\");\r\n");
      out.write("      }).mouseout(function() {\r\n");
      out.write("         $(this).removeClass(\"over\");\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   function imgclick() {\r\n");
      out.write("      var img = document.getElementById('image');\r\n");
      out.write("\r\n");
      out.write("      if (img.src.match(\"like_no\")) {\r\n");
      out.write("         img.src = \"/semi/images/like_yes.png\";\r\n");
      out.write("      } else {\r\n");
      out.write("         img.src = \"/semi/images/like_no.png\";\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   $(\".hover\").mouseleave(\r\n");
      out.write("          function() {\r\n");
      out.write("            $(this).removeClass(\"hover\");\r\n");
      out.write("          }\r\n");
      out.write("        );\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   function insert(){\r\n");
      out.write("         \r\n");
      out.write("         alert('입력되었습니다');\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      function deleter(){\r\n");
      out.write("         alert('삭제되었습니다');\r\n");
      out.write("         \r\n");
      out.write("      }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");

	Member member = (Member) session.getAttribute("member");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"css/1-col-portfolio.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@import url(//fonts.googleapis.com/earlyaccess/nanumpenscript.css);\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: 'Nanum Pen Script', cursive;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\tborder-collapse: separate;\r\n");
      out.write("\tborder-spacing: 0px 4px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-dialog {\r\n");
      out.write("\twidth: 450px;\r\n");
      out.write("\theight: 350px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@import url(//fonts.googleapis.com/earlyaccess/nanumpenscript.css);\r\n");
      out.write("\r\n");
      out.write(".npss {\r\n");
      out.write("\tfont-family: 'Nanum Pen Script', cursive;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nps {\r\n");
      out.write("\tfont-family: 'Nanum Pen Script', cursive;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.linkcolor {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #888;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("a.linkcolor:hover {\r\n");
      out.write("\tcolor:#369;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav\r\n");
      out.write("\t\tclass=\"navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand npss\" href=\"intro.jsp\">WhybiS</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler navbar-toggler-right\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbarResponsive\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarResponsive\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse nps\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/semi/intro.jsp\">HOME</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t");

							if (member != null) {
						
      out.write(" <a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/semi/vrimg?place=홍대&title=홍대정문&userid=");
      out.print(member.getSmemberId());
      out.write("&bnum=1\">PLACE</a>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write(" <a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:alert('회원만 사용 가능 합니다 !\\n로그인을 해주세요!');\">PLACE</a>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t");

						if (member != null) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/semi/bestplace?page=1\">BEST</a></li>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/semi/bestplace?page=1\">BEST</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"\" id=\"navbarDropdownBlog\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">BOARD</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"navbarDropdownBlog\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/semi/rblist?page=1\">리뷰 게시판</a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								if ((member != null && member.getSmemberWorkerYN().equals("y"))
										|| (member != null && member.getSmemberAdminYN().equals("y"))) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/semi/wblist?page=1\">사업자게시판</a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"javascript:alert('사업자와 관리자만 게시판 열람 가능합니다 !');\">사업자게시판</a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/semi/nlist?page=1\"> NOTICE </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/semi/qlist?page=1\"> Q&A </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t");

							if (member == null) { //로그인하지 않았다면
						
      out.write(" <a class=\"nav-link dropdown-toggle\" href=\"\"\r\n");
      out.write("\t\t\t\t\t\tid=\"navbarDropdownBlog\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> MY PAGE </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"navbarDropdownBlog\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"javascript:alert('로그인이 필요합니다!');\">내\r\n");
      out.write("\t\t\t\t\t\t\t\t정보 보기 및 수정</a> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"javascript:alert('로그인이 필요합니다!');\">나의 관심 장소 보기</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"javascript:alert('로그인이 필요합니다!');\">내가\r\n");
      out.write("\t\t\t\t\t\t\t\t쓴 글 보기</a>\r\n");
      out.write("\t\t\t\t\t\t</div> ");

 	} else {
 
      out.write(" <a class=\"nav-link dropdown-toggle\" href=\"\" id=\"navbarDropdownBlog\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\tMY PAGE </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"navbarDropdownBlog\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/semi/myinfo?userid=");
      out.print(member.getSmemberId());
      out.write("\">내 정보\r\n");
      out.write("\t\t\t\t\t\t\t\t보기 및 수정</a> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/semi/mlikeplacelist?userid=");
      out.print(member.getSmemberId());
      out.write("\">나의\r\n");
      out.write("\t\t\t\t\t\t\t\t관심 장소 보기</a> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/semi/rmblist?myId=");
      out.print(member.getSmemberId());
      out.write("\">내가 쓴 글\r\n");
      out.write("\t\t\t\t\t\t\t\t보기</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div> ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li></li>\r\n");
      out.write("\t\t\t\t\t<li></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					if (member == null) { //로그인하지 않았다면
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\"#myModal\"> LOGIN </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"views/member/JoinworkerCheck.jsp\"> JOIN </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\"#myModal\"> <font color=\"white\"><b>");
      out.print(member.getSmemberName());
      out.write("</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t님</font></a></li> &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/logout\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					if (member.getSmemberId().equals("admin01")) {
				
      out.write("\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;<a href=\"/semi/mlist?page=1\" class=\"linkcolor\">회원 정보\r\n");
      out.write("\t\t\t\t\t전체보기</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t");

				if (member != null && member.getSmemberId().equals("admin01")) {
			
      out.write("\r\n");
      out.write("\t\t\t<a href=\"/semi/views/vrBoard/workerWriter.jsp\"><input\r\n");
      out.write("\t\t\t\ttype=\"submit\" class=\"btn btn-primary\" value=\"사업자 글 올리기\"></a> <a\r\n");
      out.write("\t\t\t\thref=\"/semi/vrworkerlist?page=1\"><input type=\"submit\"\r\n");
      out.write("\t\t\t\tclass=\"btn btn-primary\" value=\"올린 글 목록 보기\"></a> <br> <br>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div align=\"center\" id=\"divv\">\r\n");
      out.write("\t\t\t<form action=\"/semi/searchall\">\r\n");
      out.write("\t\t\t\t<select name=\"searchoption\">\r\n");
      out.write("\t\t\t\t\t<option value=\"all\">검색 옵션</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"명소\">장소</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"편의시설\">편의 시설</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"숙소\">숙소</option>\r\n");
      out.write("\t\t\t\t</select> &nbsp;&nbsp;&nbsp; <input type=\"hidden\" name=\"page\" value=\"1\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"searchkey\"> &nbsp;&nbsp; <input\r\n");
      out.write("\t\t\t\t\ttype=\"submit\" class=\"btn btn-primary\" value=\"검색\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<Br>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">로그인</h4>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">×</span><span class=\"sr-only\">Close</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--모달 바디-->\r\n");
      out.write("\t\t\t\t<form action=\"login\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<table width=\"250\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"userid\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>암 호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" name=\"userpwd\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\"><a href=\"#\">아이디/암호 찾기</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\"><a href=\"#\">회원가입</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!--    <script src=\"http://googledrive.com/host/0B-QKv6rUoIcGREtrRTljTlQ3OTg\"></script>\r\n");
      out.write("   ie10-viewport-bug-workaround.js\r\n");
      out.write("   <script src=\"http://googledrive.com/host/0B-QKv6rUoIcGeHd6VV9JczlHUjg\"></script> -->\r\n");
      out.write("\t<!-- holder.js -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   ");
if(maplocation!=null) {
      out.write("\r\n");
      out.write("       <input type=\"hidden\" id = \"mapname\"value=\"");
      out.print(maplocation.getMapname());
      out.write("\"> \r\n");
      out.write("       ");
} 
      out.write("\r\n");
      out.write("   <div class=\"row\">\r\n");
      out.write("   <div class=\"mainmain1\">\r\n");
      out.write("   <dl class=\"npps\" width=10%; height=10%;>\r\n");
      out.write("      \r\n");
      out.write("      <dt>홍대</dt>\r\n");
      out.write("      <dd>\r\n");
      out.write("      <table class=\"type031\">\r\n");
      out.write("      ");
for(vrBoard vr : listAll){ 
      if(vr.getVrboardtitle().contains("홍대")){ 
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("      ");
if(member!=null){ 
      out.write("\r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=홍대&userid=");
      out.print(member.getSmemberId());
      out.write('"');
      out.write('>');
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
}else{
      out.write("         \r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=홍대\">");
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
 }
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
}} 
      out.write("\r\n");
      out.write("      </table></dd>\r\n");
      out.write("      \r\n");
      out.write("      <dt>건대</dt>\r\n");
      out.write("      <dd>\r\n");
      out.write("      <table class=\"type031\">\r\n");
      out.write("      ");
for(vrBoard vr : listAll){ 
      if(vr.getVrboardtitle().contains("건대")){ 
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("      ");
if(member!=null){ 
      out.write("\r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=건대&userid=");
      out.print(member.getSmemberId());
      out.write('"');
      out.write('>');
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
}else{
      out.write("         \r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=건대\">");
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
 }
      out.write("\r\n");
      out.write(" \r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
}} 
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("      </dd>\r\n");
      out.write("      \r\n");
      out.write("      <dt>동대문</dt>\r\n");
      out.write("      <dd>\r\n");
      out.write("      <table class=\"type031\">\r\n");
      out.write("      ");
for(vrBoard vr : listAll){ 
      if(vr.getVrboardtitle().contains("동대문")){ 
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("      ");
if(member!=null){ 
      out.write("\r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=동대문&userid=");
      out.print(member.getSmemberId());
      out.write('"');
      out.write('>');
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
}else{
      out.write("         \r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=동대문\">");
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
 }
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
}} 
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dt>혜화</dt>\r\n");
      out.write("      <dd>\r\n");
      out.write("      <table class=\"type031\">\r\n");
      out.write("      ");
for(vrBoard vr : listAll){ 
      if(vr.getVrboardtitle().contains("혜화")){ 
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("      ");
if(member!=null){ 
      out.write("\r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=혜화&userid=");
      out.print(member.getSmemberId());
      out.write('"');
      out.write('>');
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
}else{
      out.write("         \r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=혜화\">");
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
 }
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
}} 
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dt>신사</dt>\r\n");
      out.write("      <dd>\r\n");
      out.write("      <table class=\"type031\">\r\n");
      out.write("      ");
for(vrBoard vr : listAll){ 
      if(vr.getVrboardtitle().contains("신사")){ 
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("      ");
if(member!=null){ 
      out.write("\r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=신사&userid=");
      out.print(member.getSmemberId());
      out.write('"');
      out.write('>');
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
}else{
      out.write("         \r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=신사\">");
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
 }
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
}} 
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("      </dd>\r\n");
      out.write("\r\n");
      out.write("      <dt>잠실</dt>\r\n");
      out.write("      <dd>\r\n");
      out.write("      <table class=\"type031\">\r\n");
      out.write("      ");
for(vrBoard vr : listAll){ 
      if(vr.getVrboardtitle().contains("잠실")){ 
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("      ");
if(member!=null){ 
      out.write("\r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=잠실&userid=");
      out.print(member.getSmemberId());
      out.write('"');
      out.write('>');
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
}else{
      out.write("         \r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=잠실\">");
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
 }
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
}} 
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("      </dd>\r\n");
      out.write("       <dt>남산</dt>\r\n");
      out.write("      <dd>\r\n");
      out.write("      <table class=\"type031\">\r\n");
      out.write("      ");
for(vrBoard vr : listAll){ 
      if(vr.getVrboardtitle().contains("남산")){ 
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("      ");
if(member!=null){ 
      out.write("\r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=남산&userid=");
      out.print(member.getSmemberId());
      out.write('"');
      out.write('>');
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
}else{
      out.write("         \r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=남산\">");
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
 }
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
}} 
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dt>명동</dt>\r\n");
      out.write("      <dd>\r\n");
      out.write("      <table class=\"type031\">\r\n");
      out.write("      ");
for(vrBoard vr : listAll){ 
      if(vr.getVrboardtitle().contains("명동")){ 
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("      ");
if(member!=null){ 
      out.write("\r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=명동&userid=");
      out.print(member.getSmemberId());
      out.write('"');
      out.write('>');
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
}else{
      out.write("         \r\n");
      out.write("         <th scope=\"row\"><a href=\"/semi/vrimg?bnum=");
      out.print(vr.getVrboardnum() );
      out.write("&title=");
      out.print(vr.getVrboardtitle());
      out.write("&place=명동\">");
      out.print(vr.getVrboardtitle());
      out.write("</a></th>\r\n");
      out.write("      ");
 }
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
}} 
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("      </dd>\r\n");
      out.write("   </dl>\r\n");
      out.write("   </div>\r\n");
      out.write("   <br><br>\r\n");
      out.write("   <!-- Page Content -->\r\n");
if(board != null){ 
      out.write("   \r\n");
      out.write("<div class = \"mainmain2\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Page Heading -->\r\n");
      out.write("      <br><br>\r\n");
      out.write("      <h1 class=\"my-4\">\r\n");
      out.write("      <small></small>\r\n");
      out.write("      </h1>\r\n");
      out.write("\r\n");
      out.write("      <!-- Project One -->\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <div align = \"center\">\r\n");
      out.write("         <div class=\"coll\">\r\n");
      out.write("            ");
if(maplocation != null){ 
      out.write("\r\n");
      out.write("          <img width=70%; height=200px; src=\"images/");
      out.print(maplocation.getImagename());
      out.write("\">\r\n");
      out.write("          <br>\r\n");
      out.write("          <a class=\"npps2\" style=\"text-align:right;\" >");
      out.print(board.getVrboardtitle());
      out.write("</a>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write(" <hr>\r\n");
      out.write("          <br><br><br><br>\r\n");
      out.write("            <form>\r\n");
      out.write("            <h1>VR PANORAMA</h1>\r\n");
      out.write("            \r\n");
      out.write("            <input type=\"hidden\" id=\"vrimages0\" value=\"images/");
      out.print(board.getVrboardoriginalfilename());
      out.write("\">\r\n");
      out.write("            </form>\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            <div id=\"map\"></div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"coll\">\r\n");
      out.write("         \r\n");
      out.write("         ");
if(member != null && like != null){
            i:for(likePlace lk:like){
               
               if(flag==false){
               if(count<like.size()){
               if(board.getVrboardnum()==lk.getLikePlaceNum() && lk.getLikeUser().equals(member.getSmemberId())){ 
      out.write("\r\n");
      out.write("               <h3>");
      out.print(board.getVrboardtitle());
      out.write("&nbsp;<a href=\"/semi/vrBoardUnlike?bnum=");
      out.print(lk.getLikePlaceNum());
      out.write("&userid=");
      out.print(member.getSmemberId());
      out.write("&placeNum=");
      out.print(board.getVrboardnum());
      out.write("&title=");
      out.print(board.getVrboardtitle());
      out.write("&place=");
      out.print(placeName );
      out.write("\"><img src =\" images/like_yes.png\"></a></h3>\r\n");
      out.write("               ");
  count++; flag=true; continue i;
               }}}}
         if(flag== false){
      out.write("\r\n");
      out.write("         <h3>");
      out.print(board.getVrboardtitle());
      out.write("&nbsp;<a href=\"/semi/vrBoardlike?bnum=");
      out.print(board.getVrboardnum());
      out.write("&userid=");
      out.print(member.getSmemberId());
      out.write("&placeNum=");
      out.print(board.getVrboardnum());
      out.write("&title=");
      out.print(board.getVrboardtitle());
      out.write("&place=");
      out.print(placeName );
      out.write("\"><img src =\" images/like_no.png\"></a></h3>\r\n");
      out.write("               \r\n");
      out.write("            ");
}}else{
      out.write("\r\n");
      out.write("         <h3>");
      out.print(board.getVrboardtitle());
      out.write("&nbsp;<a href=\"javascript:alert('로그인이 필요합니다!');\"><img src =\" images/like_no.png\"></a></h3>\r\n");
      out.write("      ");
}
      out.write("\r\n");
      out.write("          <!-- <a class=\"btn btn-primary\" href=\"#\">자세히보기</a> -->\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write(" ");
if(vbd != null){ 
      out.write("\r\n");
      out.write("   <a class=\"n4\">주소&nbsp;:&nbsp;");
      out.print(vbd.getVrdetailaddress() );
      out.write("<br>\r\n");
      out.write("   이용시간&nbsp;:&nbsp;");
      out.print(vbd.getVropentime() );
      out.write("<br>\r\n");
      out.write("   PHONE&nbsp;:&nbsp;");
      out.print(vbd.getVrphone() );
      out.write("<br>\r\n");
      out.write("   Home-Page&nbsp;:&nbsp;");
if(vbd.getVrhomepage() != null){ 
      out.write("\r\n");
      out.write("   <a class=\"homepage\" href=\"");
      out.print(vbd.getVrhomepage() );
      out.write('"');
      out.write('>');
      out.print(vbd.getVrhomepage() );
      out.write("</a>\r\n");
      out.write("   ");
}else{
      out.write("\r\n");
      out.write("   없음</a>\r\n");
      out.write("   ");
}
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   ");
} 
      out.write("\r\n");
      out.write("          \r\n");
      out.write("          <!-- <a class=\"btn btn-primary\" href=\"#\">자세히보기</a> -->\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write(" <hr>\r\n");
      out.write("  <!--  편의시설 구역 -->\r\n");
      out.write("  <h1>편의시설</h1>\r\n");
      out.write("  <div id=\"res\">\r\n");
      out.write("  ");
 for(int i =0; i<resBoard.size(); i++){
    if(resCount!=0 && resCount % 3 == 0){       
   
      out.write("\r\n");
      out.write("   ");
for(int j=0; j<resBoardDetail.size(); j++){ 
              if(i==j){ 
      out.write("\r\n");
      out.write("<figure class=\"snip1141\">\r\n");
      out.write("     <br><br><a  data-toggle=\"modal\"data-target=\"#myModal2\"><img src = \"images/");
      out.print(resBoard.get(i).getVrboardoriginalfilename());
      out.write("\" \r\n");
      out.write("     onclick=\"showimg('");
      out.print(resBoard.get(i).getVrboardoriginalfilename());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(resBoard.get(i).getVrboardtitle());
      out.write("',\r\n");
      out.write("      '");
      out.print(resBoard.get(i).getVrboardcontent());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(resBoardDetail.get(j).getVrdetailaddress());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(resBoardDetail.get(j).getVropentime());
      out.write("',\r\n");
      out.write("     '");
      out.print(resBoardDetail.get(j).getVrphone());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(resBoardDetail.get(j).getVrhomepage());
      out.write(");\"width=\"250px\" height=\"250px\" ></a>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<figcaption>\r\n");
      out.write("    <div class=\"circle\"><i class=\"ion-ios-plus-empty\"> </i></div>\r\n");
      out.write("    <h3 >");
      out.print(resBoard.get(i).getVrboardtitle());
      out.write("</h3>\r\n");
      out.write("  </figcaption>\r\n");
      out.write("  </figure> \r\n");
      out.write(" ");
}}
      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.write("\r\n");
      out.write("              \r\n");
      out.write("  \r\n");
      out.write("   ");
 f=true;}else{ 
   
      out.write("\r\n");
      out.write("   ");
for(int j=0; j<resBoardDetail.size(); j++){ 
              if(i==j){ 
      out.write("\r\n");
      out.write("  <figure class=\"snip1141\">\r\n");
      out.write("     <a  data-toggle=\"modal\" data-target=\"#myModal2\" ><img src = \"images/");
      out.print(resBoard.get(i).getVrboardoriginalfilename());
      out.write("\"\r\n");
      out.write("      onclick=\"showimg('");
      out.print(resBoard.get(i).getVrboardoriginalfilename());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(resBoard.get(i).getVrboardtitle());
      out.write("',\r\n");
      out.write("      '");
      out.print(resBoard.get(i).getVrboardcontent());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(resBoardDetail.get(j).getVrdetailaddress());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(resBoardDetail.get(j).getVropentime());
      out.write("',\r\n");
      out.write("     '");
      out.print(resBoardDetail.get(j).getVrphone());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(resBoardDetail.get(j).getVrhomepage());
      out.write("');\"width=\"250px\" height=\"250px\" ></a>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<figcaption>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"circle\"><i class=\"ion-ios-plus-empty\"> </i></div>\r\n");
      out.write("    <h3 >");
      out.print(resBoard.get(i).getVrboardtitle());
      out.write("</h3>\r\n");
      out.write("  </figcaption>\r\n");
      out.write("  </figure>\r\n");
      out.write("  ");
}} 
      out.write("\r\n");
      out.write("   \r\n");
      out.write("               \r\n");
      out.write("     ");
 f=true;}resCount++;
      out.write("\r\n");
      out.write("      <div class=\"modal fade\" id=\"myModal2\" tabindex=\"-1\" role=\"dialog\" \r\n");
      out.write("    area-labelleby=\"myBodalLabel\" aria-hidden=\"true\" style=\"clear:both\">\r\n");
      out.write("               <div class=\"modal-dialog\">\r\n");
      out.write("               <div class=\"modal-content\">\r\n");
      out.write("            \r\n");
      out.write("               <div class =\"insta-back\" ><!-- 내용 -->\r\n");
      out.write("            <div class=\"modal-header\"><!-- x -->\r\n");
      out.write("            <h3 id =\"restitle\"></h3> \r\n");
      out.write("               <button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("               <span aria-hidden=\"true\">×</span>\r\n");
      out.write("               <span class=\"sr-only\">Close</span></button>\r\n");
      out.write("               </div><!-- x -->\r\n");
      out.write("      \r\n");
      out.write("               <div class=\"insta\">\r\n");
      out.write("               <div class=\"insta ga\">\r\n");
      out.write("               \r\n");
      out.write("               <img id =\"resimg1\" src=\"\" width=100%; height=100%;></img>\r\n");
      out.write("            \r\n");
      out.write("                   </div>\r\n");
      out.write("                        <!-- 사진 -->\r\n");
      out.write("                  <div class=\"insta se\" style=\"overflow:scroll\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                  <p id=\"rescont\" class=\"n5\"></p>\r\n");
      out.write("                  <b><p id=\"restitle2\" class=\"n5\"></p></b>\r\n");
      out.write("                  <p id=\"resadd\" class=\"n5\"></p>\r\n");
      out.write("                  <p id=\"resopentime\" class=\"n5\"></p>\r\n");
      out.write("                  <p id=\"resphone\" class=\"n5\"></p>\r\n");
      out.write("                  <a id=\"reslink\" class=\"n5 homepage\" href=\"\"><p id=\"reshomepage\" class=\"n5 homepage\"></p></a>\r\n");
      out.write("               \r\n");
      out.write("                  <hr></div>\r\n");
      out.write("                  <div>\r\n");
      out.write("                  <!-- 댓글내용 -->\r\n");
      out.write("                  <p class=\"n5\">");
      out.print(board.getVrboardtitle());
      out.write(" ↓ community  ↓</p>\r\n");
      out.write("                  ");
if(list2!=null){
      out.write("\r\n");
      out.write("                     <table style=\"boarder:none\">\r\n");
      out.write("                  ");
for(DetailComment d : list2){ 
      out.write("\r\n");
      out.write("                     <tr><td>");
      out.print(d.getDwriter());
      out.write(" : </td><td>");
      out.print(d.getDcontent());
      out.write("</td>\r\n");
      out.write("                     ");
if(member != null){ 
                     if(d.getDwriter().equals(member.getSmemberId()) || member.getSmemberId().equals("admin01")){
      out.write("\r\n");
      out.write("                     <td><a  href=\"/semi/drdelete?cno=");
      out.print(d.getCno());
      out.write("&bnum=");
      out.print(board.getVrboardnum());
      out.write("&userid=");
      out.print(member.getSmemberId() );
      out.write("&place=");
      out.print(placeName);
      out.write("&title=");
      out.print(board.getVrboardtitle());
      out.write("\" onclick=\"deleter();\">x</a></td>");
} }
      out.write("</tr>\r\n");
      out.write("                  ");
}} 
      out.write("\r\n");
      out.write("                  </table>\r\n");
      out.write("                  </div>\r\n");
      out.write("                   <div>\r\n");
      out.write("                 \r\n");
      out.write("                <form action=\"/semi/drinsert?bnum=");
      out.print(board.getVrboardnum());
      out.write("&userid=");
      out.print(member.getSmemberId() );
      out.write("&place=");
      out.print(placeName);
      out.write("&title=");
      out.print(board.getVrboardtitle());
      out.write("\" method=\"post\">\r\n");
      out.write("                  <input type=\"text\" name=\"dcontent\" placeholder=\"댓글입력...\" style=\" border-top:none; border-left:none; border-right:none;\">\r\n");
      out.write("                  <input type=\"submit\" value=\"입력\" onclick=\"insert();\">\r\n");
      out.write("                  \r\n");
      out.write("                  </form>\r\n");
      out.write("                 </div>\r\n");
      out.write(" \r\n");
      out.write("               \r\n");
      out.write("                  </div><!-- 상세정보 -->\r\n");
      out.write("            \r\n");
      out.write("                  </div> \r\n");
      out.write("               </div><!-- 내용 -->\r\n");
      out.write("       \r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("               </div>\r\n");
      out.write("  ");
} 
      out.write("\r\n");
      out.write("     \r\n");
      out.write("          \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("             </div>\r\n");
      out.write("           \r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("function showimg(val,val2,val3,add,time,phone,home){\r\n");
      out.write("   console.log(val);\r\n");
      out.write("   document.getElementById(\"resimg1\").src=\"images/\"+val;\r\n");
      out.write("   document.getElementById(\"restitle\").innerHTML=val2;\r\n");
      out.write("   document.getElementById(\"rescont\").innerHTML=val3;\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   document.getElementById(\"restitle2\").innerHTML=val2;\r\n");
      out.write("   document.getElementById(\"resadd\").innerHTML=add;\r\n");
      out.write("   document.getElementById(\"resopentime\").innerHTML=time;\r\n");
      out.write("   document.getElementById(\"resphone\").innerHTML=phone;\r\n");
      out.write("   \r\n");
      out.write("   document.getElementById(\"reslink\").href=home;\r\n");
      out.write("   if(home != 'null'){\r\n");
      out.write("   document.getElementById(\"reshomepage\").innerHTML=home;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("</script>   \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("  <hr style=\"clear:both\">\r\n");
      out.write("         <h1>LOCATION</h1>\r\n");
      out.write("            \r\n");
      out.write("<div id=\"map1\" style=\"width:70%;height:350px;\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=767bb21ee012c29905e704cc8310cffa\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("var mapContainer = document.getElementById('map1'), // 지도를 표시할 div \r\n");
      out.write("    mapOption = { \r\n");
      out.write("        center: new daum.maps.LatLng(");
      out.print(maplocation.getMapwi());
      out.write(',');
      out.print(maplocation.getMapkung());
      out.write(" ), // 지도의 중심좌표\r\n");
      out.write("        level: 4 // 지도의 확대 레벨\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("// 지도를 표시할 div와  지도 옵션으로  지도를 생성합니다\r\n");
      out.write("var map = new daum.maps.Map(mapContainer, mapOption); \r\n");
      out.write("//마커가 표시될 위치입니다 \r\n");
      out.write("var position  = new daum.maps.LatLng(");
      out.print(maplocation.getMapwi());
      out.write(',');
      out.print(maplocation.getMapkung());
      out.write("); \r\n");
      out.write("\r\n");
      out.write("// 마커를 생성합니다\r\n");
      out.write("var marker = new daum.maps.Marker({\r\n");
      out.write("  position: position,\r\n");
      out.write("  clickable: true // 마커를 클릭했을 때 지도의 클릭 이벤트가 발생하지 않도록 설정합니다\r\n");
      out.write("});\r\n");
      out.write("marker.setMap(map);\r\n");
      out.write("var mapname=document.getElementById('mapname').value;\r\n");
      out.write("var iwContent = '<div style=\"padding:5px;\"><p class=\"npps\" style=\"font-size:27px;\">'+mapname+'<P></div>', // 인포윈도우에 표출될 내용으로 HTML 문자열이나 document element가 가능합니다\r\n");
      out.write("iwRemoveable = true; // removeable 속성을 ture 로 설정하면 인포윈도우를 닫을 수 있는 x버튼이 표시됩니다\r\n");
      out.write("\r\n");
      out.write("//인포윈도우를 생성합니다\r\n");
      out.write("// 인포윈도우를 생성합니다\r\n");
      out.write("var infowindow = new daum.maps.InfoWindow({\r\n");
      out.write("    content : iwContent,\r\n");
      out.write("    removable : iwRemoveable\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// 마커에 클릭이벤트를 등록합니다\r\n");
      out.write("daum.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("      // 마커 위에 인포윈도우를 표시합니다\r\n");
      out.write("      infowindow.open(map, marker);  \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div align = \"center\">\r\n");
      out.write("   ");
} 
      out.write("\r\n");
      out.write("   <h3>오시는길</h3>\r\n");
      out.write("   ");
if(maplocation != null){ 
      out.write("\r\n");
      out.write("   <a class=\"n3\">");
      out.print(maplocation.getGbus());
      out.write("</a><br>\r\n");
      out.write("   <a class=\"n3\">");
      out.print(maplocation.getMbus());
      out.write("</a><br>\r\n");
      out.write("   <a class=\"n3\">지하철:");
      out.print(maplocation.getMetro());
      out.write("</a><br>\r\n");
      out.write("   ");
} 
      out.write("\r\n");
      out.write("   <!--오른쪽 전체  -->\r\n");
      out.write("  </div> \r\n");
      out.write("   </div>\r\n");
      out.write("  <div class=\"floating\" align = \"center\">\r\n");
      out.write("  <div class = \"infloating\" width = \"100%\" height = \"45px\">\r\n");
      out.write("     <font size = \"5px\"><b>[ WhybiS광고글 ]</b><br></font>\r\n");
      out.write("     <font size = \"4px\">누르면 해당 홈페이지로 이동합니다!</font>\r\n");
      out.write("     <br>\r\n");
      out.write("  </div>\r\n");
      out.write("  <br>\r\n");
      out.write("   <a href = \"http://www.yanolja.com\" target=\"_blank\">\r\n");
      out.write("   <!-- 광고 -->\r\n");
      out.write("      <img src = \"images/yanolja.gif\" width = \"90%\" >\r\n");
      out.write("   </a>\r\n");
      out.write("   <br><br>\r\n");
      out.write("      <a href = \"http://corp.dailyhotel.co.kr\" target=\"_blank\">\r\n");
      out.write("   <!-- 광고 -->\r\n");
      out.write("      <img src = \"images/daily.gif\" width = \"90%\" >\r\n");
      out.write("   </a>\r\n");
      out.write("   \r\n");
      out.write("     <br><br>\r\n");
      out.write("         <a href = \"http://www.goodchoice.kr\" target=\"_blank\">\r\n");
      out.write("   <!-- 광고 -->\r\n");
      out.write("      <img src = \"images/zzz.gif\" width = \"90%\" >\r\n");
      out.write("      <br>\r\n");
      out.write("   </a>\r\n");
      out.write("   <br>\r\n");
      out.write("   ");
if(member!=null) { 
      out.write("\r\n");
      out.write("      <a href = \"/semi/mlikeplacelist?userid=");
      out.print(member.getSmemberId());
      out.write("\">\r\n");
      out.write("   <!-- 광고 -->\r\n");
      out.write("      <img src = \"/semi/images/likeit.jpg\" width = \"80px\" height = \"60px\" >\r\n");
      out.write("   </a>\r\n");
      out.write("   ");
} else { 
      out.write("\r\n");
      out.write("   <a href = \"javascript:alert('로그인이 필요합니다!');\">\r\n");
      out.write("   <!-- 광고 -->\r\n");
      out.write("      <img src = \"/semi/images/likeit.jpg\" width = \"80px\" height = \"60px\" >\r\n");
      out.write("   </a>\r\n");
      out.write("   ");
} 
      out.write("\r\n");
      out.write("   <br>\r\n");
      out.write("   <font size = \"4px\">관심 목록 보기</font>\r\n");
      out.write("   <br>\r\n");
      out.write("   <div class = \"ininfloat\">\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <font size = \"5px\"><a id = \"MOVE_TOP_BTN\" style=\"cursor:pointer\">▲ TOP</a></font>\r\n");
      out.write("   <br>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("<!--    <div class=\"mainmain3\" align = \"center\">\r\n");
      out.write("   <a href = \"http://www.yanolja.com\" target=\"_blank\">\r\n");
      out.write("      <img src = \"images/gwanggo.png\" width = \"50%\" height = \"550px;\">\r\n");
      out.write("   </a>\r\n");
      out.write("   </div>\r\n");
      out.write(" -->\r\n");
      out.write("   </div><!-- 화면 전체  -->\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("      <hr>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCslBH2Gcxh8pTTDRpLOlrEJ6RpOMjXwZ4&callback=initPano\"\r\n");
      out.write("      async defer>\r\n");
      out.write("   </script>\r\n");
      out.write("   <script>\r\n");
      out.write("   var filePath = document.getElementById(\"vrimages0\").value;\r\n");
      out.write("   \r\n");
      out.write("   console.log(filePath);\r\n");
      out.write("   \r\n");
      out.write("   function initPano() {\r\n");
      out.write("         // Set up Street View and initially set it visible. Register the\r\n");
      out.write("         // custom panorama provider function. Set the StreetView to display\r\n");
      out.write("         // the custom panorama 'reception' which we check for below.\r\n");
      out.write("         var panorama = new google.maps.StreetViewPanorama(document.getElementById('map'), {\r\n");
      out.write("            pano : 'reception',\r\n");
      out.write("            visible : true,\r\n");
      out.write("            panoProvider : getCustomPanorama\r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("      \r\n");
      out.write("      // Return a pano image given the panoID.\r\n");
      out.write("      function getCustomPanoramaTileUrl(pano, zoom, tileX, tileY) {\r\n");
      out.write("         // Note: robust custom panorama methods would require tiled pano data.\r\n");
      out.write("         // Here we're just using a single tile, set to the tile size and equal\r\n");
      out.write("         // to the pano \"world\" size.\r\n");
      out.write("         return filePath;\r\n");
      out.write("      \r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // Construct the appropriate StreetViewPanoramaData given\r\n");
      out.write("      // the passed pano IDs.\r\n");
      out.write("      function getCustomPanorama(pano, zoom, tileX, tileY) {\r\n");
      out.write("         if (pano === 'reception') {\r\n");
      out.write("            return {\r\n");
      out.write("               location : {\r\n");
      out.write("                  pano : 'reception',\r\n");
      out.write("                  description : ''\r\n");
      out.write("               },\r\n");
      out.write("               links : [],\r\n");
      out.write("               // The text for the copyright control.\r\n");
      out.write("               copyright : 'sexy',\r\n");
      out.write("               // The definition of the tiles for this panorama.\r\n");
      out.write("               tiles : {\r\n");
      out.write("                  tileSize : new google.maps.Size(673, 411),\r\n");
      out.write("                  worldSize : new google.maps.Size(673, 411),\r\n");
      out.write("                  // The heading in degrees at the origin of the panorama\r\n");
      out.write("                  // tile set.\r\n");
      out.write("                  centerHeading : 105,\r\n");
      out.write("                  getTileUrl : getCustomPanoramaTileUrl\r\n");
      out.write("               }\r\n");
      out.write("            };\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      vrView.addHotspot('123', {\r\n");
      out.write("         pitch : 30, // In degrees. Up is positive.\r\n");
      out.write("         yaw : 20, // In degrees. To the right is positive.\r\n");
      out.write("         radius : 10, // Radius of the circular target in meters.\r\n");
      out.write("         distance : 2\r\n");
      out.write("      // Distance of target from camera in meters.\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      vrView.on('click', function(event) {\r\n");
      out.write("         if (event.id == myHotspotId) {\r\n");
      out.write("            // Handle hotspot click.\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("@import url(//fonts.googleapis.com/earlyaccess/nanumpenscript.css);\r\n");
      out.write("p{ font-family: 'Nanum Pen Script', cursive; font-size:30px; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"jquery/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"jquery/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("   <script src=\"jqueryintro/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer class=\"py-5 bg-dark\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<p class=\"m-0 text-center text-white\">Copyright &copy; Your\r\n");
      out.write("\t\t\t\tWebsite 2018</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container -->\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
