/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2018-01-26 11:37:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reviewComment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>reviewComment</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <!-- meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0\"/ -->\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title></title>\r\n");
      out.write("        <!-- Bootstrap -->\r\n");
      out.write("        <link href=\"./bootstrap/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("        <!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요한) -->\r\n");
      out.write("        <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <!-- 좌우측의 공간 확보 -->\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <hr/>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-10\">\r\n");
      out.write("                    <table class=\"table table-condensed\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr align=\"center\">\r\n");
      out.write("                                <th width=\"10%\">제목</th>\r\n");
      out.write("                                <th width=\"60%\">게시판 제목 입니다.</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>작성일\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                2018-01-26\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>글쓴이\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                husk <span style='float:right'>조회 : 0</span>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td colspan=\"2\">\r\n");
      out.write("                                    <p>이름, 패스워드 내용을 적으시고 확인버튼을 누르세요.</p>\r\n");
      out.write("                        \r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <table id=\"commentTable\" class=\"table table-condensed\"></table>\r\n");
      out.write("                    <table class=\"table table-condensed\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <span class=\"form-inline\" role=\"form\">\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"text\" id=\"commentParentName\" name=\"commentParentName\" class=\"form-control col-lg-2\" data-rule-required=\"true\" placeholder=\"이름\" maxlength=\"10\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"password\" id=\"commentParentPassword\" name=\"commentParentPassword\" class=\"form-control col-lg-2\" data-rule-required=\"true\" placeholder=\"패스워드\" maxlength=\"10\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <button type=\"button\" id=\"commentParentSubmit\" name=\"commentParentSubmit\" class=\"btn btn-default\">확인</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                        <textarea id=\"commentParentText\" class=\"form-control col-lg-12\" style=\"width:100%\" rows=\"4\"></textarea>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <table class=\"table table-condensed\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <span style='float:right'>\r\n");
      out.write("                                        <button type=\"button\" id=\"list\" class=\"btn btn-default\">목록</button>\r\n");
      out.write("                                        <button type=\"button\" id=\"modify\" class=\"btn btn-default\">수정</button>\r\n");
      out.write("                                        <button type=\"button\" id=\"delete\" class=\"btn btn-default\">삭제</button>\r\n");
      out.write("                                        <button type=\"button\" id=\"write\" class=\"btn btn-default\">글쓰기</button>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <script>\r\n");
      out.write("   \r\n");
      out.write("                        $(function(){\r\n");
      out.write("                               \r\n");
      out.write("                            //제일 하단에 있는 depth1의 댓글을 다는 이벤트\r\n");
      out.write("                            $(\"#commentParentSubmit\").click(function( event ) {\r\n");
      out.write("                                   \r\n");
      out.write("                                //ajax로 저장하고 성공하면 저장한 데이터를 가져와 넣어야 하는데 여기서는 테스트라 그냥 입력값을 가져옴\r\n");
      out.write("                                var pName = $(\"#commentParentName\");\r\n");
      out.write("                                var pPassword = $(\"#commentParentPassword\");//패스워드를 노출 시켰는데 저장하고 나서 저장한 날짜를 보여줄 예정\r\n");
      out.write("                                var pText = $(\"#commentParentText\");\r\n");
      out.write("                                   \r\n");
      out.write("                                if($.trim(pName.val())==\"\"){\r\n");
      out.write("                                    alert(\"이름을 입력하세요.\");\r\n");
      out.write("                                    pName.focus();\r\n");
      out.write("                                    return;\r\n");
      out.write("                                }else if($.trim(pPassword.val())==\"\"){\r\n");
      out.write("                                    alert(\"패스워드를 입력하세요.\");\r\n");
      out.write("                                    pPassword.focus();\r\n");
      out.write("                                    return;\r\n");
      out.write("                                }else if($.trim(pText.val())==\"\"){\r\n");
      out.write("                                    alert(\"내용을 입력하세요.\");\r\n");
      out.write("                                    pText.focus();\r\n");
      out.write("                                    return;\r\n");
      out.write("                                }\r\n");
      out.write("                                   \r\n");
      out.write("                                var commentParentText = '<tr id=\"r1\" name=\"commentParentCode\">'+\r\n");
      out.write("                                                            '<td colspan=2>'+\r\n");
      out.write("                                                                '<strong>'+pName.val()+'</strong> '+pPassword.val()+' <a style=\"cursor:pointer;\" name=\"pAdd\">답글</a> | <a style=\"cursor:pointer;\" name=\"pDel\">삭제</a><p>'+pText.val().replace(/\\n/g, \"<br>\")+'</p>'+\r\n");
      out.write("                                                            '</td>'+\r\n");
      out.write("                                                        '</tr>';\r\n");
      out.write("                                   \r\n");
      out.write("                                //테이블의 tr자식이 있으면 tr 뒤에 붙인다. 없으면 테이블 안에 tr을 붙인다.\r\n");
      out.write("                                if($('#commentTable').contents().size()==0){\r\n");
      out.write("                                    $('#commentTable').append(commentParentText);\r\n");
      out.write("                                }else{\r\n");
      out.write("                                    $('#commentTable tr:last').after(commentParentText);\r\n");
      out.write("                                }\r\n");
      out.write("                                   \r\n");
      out.write("                                $(\"#commentParentName\").val(\"\");\r\n");
      out.write("                                $(\"#commentParentPassword\").val(\"\");\r\n");
      out.write("                                $(\"#commentParentText\").val(\"\");\r\n");
      out.write("                                   \r\n");
      out.write("                            });\r\n");
      out.write("                               \r\n");
      out.write("                            //댓글의 댓글을 다는 이벤트\r\n");
      out.write("                            $(document).on(\"click\",\"#commentChildSubmit\", function(){\r\n");
      out.write("                                   \r\n");
      out.write("                                var cName = $(\"#commentChildName\");\r\n");
      out.write("                                var cPassword = $(\"#commentChildPassword\");\r\n");
      out.write("                                var cText = $(\"#commentChildText\");\r\n");
      out.write("                                   \r\n");
      out.write("                                if($.trim(cName.val())==\"\"){\r\n");
      out.write("                                    alert(\"이름을 입력하세요.\");\r\n");
      out.write("                                    cName.focus();\r\n");
      out.write("                                    return;\r\n");
      out.write("                                }else if($.trim(cPassword.val())==\"\"){\r\n");
      out.write("                                    alert(\"패스워드를 입력하세요.\");\r\n");
      out.write("                                    cPassword.focus();\r\n");
      out.write("                                    return;\r\n");
      out.write("                                }else if($.trim(cText.val())==\"\"){\r\n");
      out.write("                                    alert(\"내용을 입력하세요.\");\r\n");
      out.write("                                    cText.focus();\r\n");
      out.write("                                    return;\r\n");
      out.write("                                }\r\n");
      out.write("                                   \r\n");
      out.write("                                var commentChildText = '<tr name=\"commentChildCode\">'+\r\n");
      out.write("                                                            '<td style=\"width:1%\"><span class=\"glyphicon glyphicon-arrow-right\"></span></td>'+\r\n");
      out.write("                                                            '<td style=\"width:99%\">'+\r\n");
      out.write("                                                                '<strong>'+cName.val()+'</strong> '+cPassword.val()+' <a style=\"cursor:pointer;\" name=\"cAdd\">답글</a> | <a style=\"cursor:pointer;\" name=\"cDel\">삭제</a>'+\r\n");
      out.write("                                                                '<p>'+cText.val().replace(/\\n/g, \"<br>\")+'</p>'+\r\n");
      out.write("                                                            '</td>'+\r\n");
      out.write("                                                        '</tr>';\r\n");
      out.write("                                                           \r\n");
      out.write("                                //앞의 tr노드 찾기\r\n");
      out.write("                                var prevTr = $(this).parent().parent().parent().parent().prev();\r\n");
      out.write("                                //댓글 적는 에디터 삭제\r\n");
      out.write("                                $(\"#commentEditor\").remove();//여기에서 삭제를 해줘야 에디터tr을 안 찾는다.\r\n");
      out.write("                                   \r\n");
      out.write("                                //댓글을 타고 올라가며 부모 tr을 찾음\r\n");
      out.write("                                while(prevTr.attr(\"name\")!=\"commentParentCode\"){\r\n");
      out.write("                                    prevTr = prevTr.prev();\r\n");
      out.write("                                }\r\n");
      out.write("                                //while를 타는지 체크\r\n");
      out.write("                                var check = false;\r\n");
      out.write("                                //다음 노드가 댓글(depth1)의 댓글인지 찾기위해 next\r\n");
      out.write("                                var nextTr = prevTr.next();\r\n");
      out.write("                                //뒤에 댓글(depth1)의 댓글(depth2_1)이 없다면 바로 붙인다.\r\n");
      out.write("                                if(nextTr.attr(\"name\")!=\"commentChildCode\"){\r\n");
      out.write("                                    prevTr.after(commentChildText);\r\n");
      out.write("                                }else{\r\n");
      out.write("                                    //댓글(depth1)의 댓글(depth2_n)이 있는경우 마지막까지 찾는다.\r\n");
      out.write("                                    while(nextTr.attr(\"name\")==\"commentChildCode\"){\r\n");
      out.write("                                        nextTr = nextTr.next();\r\n");
      out.write("                                        check = true;\r\n");
      out.write("                                    }\r\n");
      out.write("                                }\r\n");
      out.write("                                   \r\n");
      out.write("                                if(check){//댓글(depth1)의 댓글(depth2_n)이 있다면 그 댓글(depth2_n) 뒤에 댓글(depth2_n+1) 추가\r\n");
      out.write("                                    nextTr = nextTr.prev();//while문에서 검색하느라 next로 넘거갔던거 다시 앞으로 돌려줌\r\n");
      out.write("                                    nextTr.after(commentChildText);\r\n");
      out.write("                                }\r\n");
      out.write("                                   \r\n");
      out.write("                            });\r\n");
      out.write("                               \r\n");
      out.write("                            //답글링크를 눌렀을때 에디터 창을 뿌려주는 이벤트, 삭제링크를 눌렀을때 해당 댓글을 삭제하는 이벤트\r\n");
      out.write("                            $(document).on(\"click\",\"table#commentTable a\", function(){//동적으로 버튼이 생긴 경우 처리 방식\r\n");
      out.write("                                   \r\n");
      out.write("                                if($(this).attr(\"name\")==\"pDel\"){\r\n");
      out.write("                                    if (confirm(\"답글을 삭제 하시면 밑에 답글도 모두 삭제 됩니다. 정말 삭제하시겠습니까?\") == true){    //확인\r\n");
      out.write("                                           \r\n");
      out.write("                                        var delComment = $(this).parent().parent();\r\n");
      out.write("                                        var nextTr = delComment.next();\r\n");
      out.write("                                        var delTr;\r\n");
      out.write("                                        //댓글(depth1)의 댓글(depth2_1)이 있는지 검사하여 삭제\r\n");
      out.write("                                        while(nextTr.attr(\"name\")==\"commentCode\"){\r\n");
      out.write("                                            nextTr = nextTr.next();\r\n");
      out.write("                                            delTr = nextTr.prev();//삭제하고 넘기면 삭제되서 없기 때문에 다음값을 가져오기 어려워 다시 앞으로 돌려서 찾은 다음 삭제\r\n");
      out.write("                                            delTr.remove();\r\n");
      out.write("                                        }\r\n");
      out.write("                                           \r\n");
      out.write("                                        delComment.remove();\r\n");
      out.write("                                           \r\n");
      out.write("                                    }else{   //취소\r\n");
      out.write("                                        return;\r\n");
      out.write("                                    }\r\n");
      out.write("                                }else if($(this).attr(\"name\")==\"cDel\"){\r\n");
      out.write("                                    if (confirm(\"정말 삭제하시겠습니까??\") == true){    //확인\r\n");
      out.write("                                        $(this).parent().parent().remove();\r\n");
      out.write("                                    }else{   //취소\r\n");
      out.write("                                        return;\r\n");
      out.write("                                    }\r\n");
      out.write("                                }else{\r\n");
      out.write("                                    //자기 부모의 tr을 알아낸다.\r\n");
      out.write("                                    var parentElement = $(this).parent().parent();\r\n");
      out.write("                                    //댓글달기 창을 없앤다.\r\n");
      out.write("                                    $(\"#commentEditor\").remove();\r\n");
      out.write("                                    //부모의 하단에 댓글달기 창을 삽입\r\n");
      out.write("                                    var commentEditor = '<tr id=\"commentEditor\">'+\r\n");
      out.write("                                                            '<td style=\"width:1%\"> </td>'+\r\n");
      out.write("                                                            '<td>'+\r\n");
      out.write("                                                                '<span class=\"form-inline\" role=\"form\">'+\r\n");
      out.write("                                                                    '<p>'+\r\n");
      out.write("                                                                        '<div class=\"form-group\">'+\r\n");
      out.write("                                                                            '<input type=\"text\" id=\"commentChildName\" name=\"commentChildName\" class=\"form-control col-lg-2\" data-rule-required=\"true\" placeholder=\"이름\" maxlength=\"10\">'+\r\n");
      out.write("                                                                        '</div>'+\r\n");
      out.write("                                                                        '<div class=\"form-group\">'+\r\n");
      out.write("                                                                            ' <input type=\"password\" id=\"commentChildPassword\" name=\"commentChildPassword\" class=\"form-control col-lg-2\" data-rule-required=\"true\" placeholder=\"패스워드\" maxlength=\"10\">'+\r\n");
      out.write("                                                                        '</div>'+\r\n");
      out.write("                                                                        '<div class=\"form-group\">'+\r\n");
      out.write("                                                                            '<button type=\"button\" id=\"commentChildSubmit\" class=\"btn btn-default\">확인</button>'+\r\n");
      out.write("                                                                        '</div>'+\r\n");
      out.write("                                                                    '</p>'+\r\n");
      out.write("                                                                        '<textarea id=\"commentChildText\" name=\"commentChildText\" class=\"form-control\" style=\"width:98%\" rows=\"4\"></textarea>'+\r\n");
      out.write("                                                                '</span>'+\r\n");
      out.write("                                                            '</td>'+\r\n");
      out.write("                                                        '</tr>';\r\n");
      out.write("                                                           \r\n");
      out.write("                                    parentElement.after(commentEditor); \r\n");
      out.write("                                }\r\n");
      out.write("                                   \r\n");
      out.write("                            });\r\n");
      out.write("                               \r\n");
      out.write("                            $( \"#list\" ).click(function( event ) {\r\n");
      out.write("                                location.href='/community/notice';\r\n");
      out.write("                            });\r\n");
      out.write("                            $( \"#modify\" ).click(function( event ) {\r\n");
      out.write("                                location.href='/community/modify/notice/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${community.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("                            });\r\n");
      out.write("                            $( \"#delete\" ).click(function( event ) {\r\n");
      out.write("                                location.href='/community/delete/notice/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${community.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("                            });\r\n");
      out.write("                            $( \"#write\" ).click(function( event ) {\r\n");
      out.write("                                location.href='/community/notice/edit';\r\n");
      out.write("                            });\r\n");
      out.write("                        });\r\n");
      out.write("                    </script>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr/>\r\n");
      out.write("        </div>    \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
