/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2018-01-29 14:43:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vrBoard.model.vo.vrBoard;
import java.util.*;
import member.model.vo.Member;

public final class vr_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/../../footer.jsp", Long.valueOf(1517224153540L));
    _jspx_dependants.put("/../../header.jsp", Long.valueOf(1517236467950L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("vrBoard.model.vo.vrBoard");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");

	vrBoard vrboard = (vrBoard)request.getAttribute("board");

      out.write(' ');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>1 Col Portfolio - Start Bootstrap Template</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"css/1-col-portfolio.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("html, body {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#map {\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\twidth:600px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");

	Member member = (Member)session.getAttribute("member");

      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(" table{\r\n");
      out.write("    border-collapse: separate;\r\n");
      out.write("   border-spacing:0px 4px\r\n");
      out.write(" }\r\n");
      out.write(" .modal-dialog{\r\n");
      out.write("      width:450px;\r\n");
      out.write("      height:350px;\r\n");
      out.write(" }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav\r\n");
      out.write("\t\tclass=\"navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"intro.jsp\">WhybiS</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler navbar-toggler-right\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbarResponsive\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarResponsive\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/intro.jsp\">HOME</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/views/vrboard/vr.jsp\">PLACE</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/views/best/best.jsp\">BEST</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/rblist?page=1\"> BOARD </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/qlist?page=1\"> Q&A </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"\" id=\"navbarDropdownBlog\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\tMY PAGE </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"navbarDropdownBlog\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"full-width.html\">내 정보 보기 및 수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"sidebar.html\">나의 관심 장소 보기</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"faq.html\">내가 쓴 글 보기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<li></li>\r\n");
      out.write("\t\t\t\t\t\t<li></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");
 if(member == null){  //로그인하지 않았다면 
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"modal\" data-target=\"#myModal\"> LOGIN </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"views/member/memberEnroll.jsp\"> JOIN </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<tr><td>");
      out.print( member.getSmemberName() );
      out.write(" 님 &nbsp;&nbsp;</td>\r\n");
      out.write("\t   <td><a href=\"/semi/logout\">로그아웃</a></td></tr>\r\n");
      out.write("\t   <tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t");
 if(member.getSmemberId().equals("admin01")){ 
      out.write(" \r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;<a href=\"/semi/mlist\">회원 정보 전체보기</a> ");
 }
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("         aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("         <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("               <div class=\"modal-header\">\r\n");
      out.write("               <h4 class=\"modal-title\" id=\"myModalLabel\">로그인</h4>\r\n");
      out.write("                  <button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("                     <span aria-hidden=\"true\">×</span><span class=\"sr-only\">Close</span>\r\n");
      out.write("                  </button>\r\n");
      out.write("                  \r\n");
      out.write("               </div>\r\n");
      out.write("         <!--모달 바디-->\r\n");
      out.write("          <form action=\"login\" method =\"post\">\r\n");
      out.write("               <div class=\"modal-body\">\r\n");
      out.write("               \r\n");
      out.write("                  <table width=\"250\" cellpadding=\"0\" cellspacing=\"0\"  align = \"center\">\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>아이디</td>\r\n");
      out.write("                        <td><input type=\"text\" name=\"userid\"></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     \r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>암     호</td>\r\n");
      out.write("                        <td><input type=\"password\" name=\"userpwd\"></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr align = \"center\">\r\n");
      out.write("                        <td colspan=\"2\"><a href=\"#\">아이디/암호 찾기</a></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr align = \"center\">\r\n");
      out.write("                     <td colspan=\"2\"><a href=\"#\">회원가입</a></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"modal-footer\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                 \r\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("                  </form>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!--    <script src=\"http://googledrive.com/host/0B-QKv6rUoIcGREtrRTljTlQ3OTg\"></script>\r\n");
      out.write("   ie10-viewport-bug-workaround.js\r\n");
      out.write("   <script src=\"http://googledrive.com/host/0B-QKv6rUoIcGeHd6VV9JczlHUjg\"></script> -->\r\n");
      out.write("   <!-- holder.js -->\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page Content -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Page Heading -->\r\n");
      out.write("\t\t<h1 class=\"my-4\">\r\n");
      out.write("\t\t\t마포구 <small>홍대입구</small>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Project One -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t");
if(vrboard !=null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"vrimages\" value=\"images/");
      out.print(vrboard.getVrboardoriginalfilename());
      out.write("\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"map\"></div>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t<h3>홍익대학교 입구</h3>\r\n");
      out.write("\t\t\t\t <a\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-primary\" href=\"#\">View Project</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Project Two -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t<a href=\"\"> <img class=\"img-fluid rounded mb-3 mb-md-0\"\r\n");
      out.write("\t\t\t\t\tsrc=\"http://placehold.it/700x300\" alt=\"\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t<h3>Project Two</h3>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut,\r\n");
      out.write("\t\t\t\t\todit velit cumque vero doloremque repellendus distinctio maiores\r\n");
      out.write("\t\t\t\t\trem expedita a nam vitae modi quidem similique ducimus! Velit, esse\r\n");
      out.write("\t\t\t\t\ttotam tempore.</p>\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-primary\" href=\"#\">View Project</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Project Three -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t<a href=\"\"> <img class=\"img-fluid rounded mb-3 mb-md-0\"\r\n");
      out.write("\t\t\t\t\tsrc=\"http://placehold.it/700x300\" alt=\"\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t<h3>Project Three</h3>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.\r\n");
      out.write("\t\t\t\t\tOmnis, temporibus, dolores, at, praesentium ut unde repudiandae\r\n");
      out.write("\t\t\t\t\tvoluptatum sit ab debitis suscipit fugiat natus velit excepturi\r\n");
      out.write("\t\t\t\t\tamet commodi deleniti alias possimus!</p>\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-primary\" href=\"#\">View Project</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Project Four -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"> <img class=\"img-fluid rounded mb-3 mb-md-0\"\r\n");
      out.write("\t\t\t\t\tsrc=\"http://placehold.it/700x300\" alt=\"\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t<h3>Project Four</h3>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.\r\n");
      out.write("\t\t\t\t\tExplicabo, quidem, consectetur, officia rem officiis illum aliquam\r\n");
      out.write("\t\t\t\t\tperspiciatis aspernatur quod modi hic nemo qui soluta aut eius\r\n");
      out.write("\t\t\t\t\tfugit quam in suscipit?</p>\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-primary\" href=\"#\">View Project</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Pagination -->\r\n");
      out.write("\t\t<ul class=\"pagination justify-content-center\">\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\"\r\n");
      out.write("\t\t\t\taria-label=\"Previous\"> <span aria-hidden=\"true\">&laquo;</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\"\r\n");
      out.write("\t\t\t\taria-label=\"Next\"> <span aria-hidden=\"true\">&raquo;</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCslBH2Gcxh8pTTDRpLOlrEJ6RpOMjXwZ4&callback=initPano\"\r\n");
      out.write("\t\tasync defer>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\tvar filePath = document.getElementById(\"vrimages\").value;\r\n");
      out.write("\tconsole.log(filePath);\r\n");
      out.write("\t\r\n");
      out.write("\tfunction initPano() {\r\n");
      out.write("\t\t\t// Set up Street View and initially set it visible. Register the\r\n");
      out.write("\t\t\t// custom panorama provider function. Set the StreetView to display\r\n");
      out.write("\t\t\t// the custom panorama 'reception' which we check for below.\r\n");
      out.write("\t\t\tvar panorama = new google.maps.StreetViewPanorama(document.getElementById('map'), {\r\n");
      out.write("\t\t\t\tpano : 'reception',\r\n");
      out.write("\t\t\t\tvisible : true,\r\n");
      out.write("\t\t\t\tpanoProvider : getCustomPanorama\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// Return a pano image given the panoID.\r\n");
      out.write("\t\tfunction getCustomPanoramaTileUrl(pano, zoom, tileX, tileY) {\r\n");
      out.write("\t\t\t// Note: robust custom panorama methods would require tiled pano data.\r\n");
      out.write("\t\t\t// Here we're just using a single tile, set to the tile size and equal\r\n");
      out.write("\t\t\t// to the pano \"world\" size.\r\n");
      out.write("\t\t\treturn filePath;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// Construct the appropriate StreetViewPanoramaData given\r\n");
      out.write("\t\t// the passed pano IDs.\r\n");
      out.write("\t\tfunction getCustomPanorama(pano, zoom, tileX, tileY) {\r\n");
      out.write("\t\t\tif (pano === 'reception') {\r\n");
      out.write("\t\t\t\treturn {\r\n");
      out.write("\t\t\t\t\tlocation : {\r\n");
      out.write("\t\t\t\t\t\tpano : 'reception',\r\n");
      out.write("\t\t\t\t\t\tdescription : ''\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tlinks : [],\r\n");
      out.write("\t\t\t\t\t// The text for the copyright control.\r\n");
      out.write("\t\t\t\t\tcopyright : 'sexy',\r\n");
      out.write("\t\t\t\t\t// The definition of the tiles for this panorama.\r\n");
      out.write("\t\t\t\t\ttiles : {\r\n");
      out.write("\t\t\t\t\t\ttileSize : new google.maps.Size(673, 411),\r\n");
      out.write("\t\t\t\t\t\tworldSize : new google.maps.Size(673, 411),\r\n");
      out.write("\t\t\t\t\t\t// The heading in degrees at the origin of the panorama\r\n");
      out.write("\t\t\t\t\t\t// tile set.\r\n");
      out.write("\t\t\t\t\t\tcenterHeading : 105,\r\n");
      out.write("\t\t\t\t\t\tgetTileUrl : getCustomPanoramaTileUrl\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvrView.addHotspot('123', {\r\n");
      out.write("\t\t\tpitch : 30, // In degrees. Up is positive.\r\n");
      out.write("\t\t\tyaw : 20, // In degrees. To the right is positive.\r\n");
      out.write("\t\t\tradius : 10, // Radius of the circular target in meters.\r\n");
      out.write("\t\t\tdistance : 2\r\n");
      out.write("\t\t// Distance of target from camera in meters.\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvrView.on('click', function(event) {\r\n");
      out.write("\t\t\tif (event.id == myHotspotId) {\r\n");
      out.write("\t\t\t\t// Handle hotspot click.\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"jquery/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"jquery/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("   <script src=\"jqueryintro/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer class=\"py-5 bg-dark\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<p class=\"m-0 text-center text-white\">Copyright &copy; Your\r\n");
      out.write("\t\t\t\tWebsite 2018</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container -->\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
