/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2018-04-16 06:08:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1520406738000L));
    _jspx_dependants.put("jar:file:/C:/finalProject5/finalProject2/finalPro/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Basic Page Needs\r\n");
      out.write("  ================================================== -->\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<title>Travel Stargram</title>\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Mobile Specific Metas\r\n");
      out.write("  ================================================== -->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- CSS\r\n");
      out.write("  ================================================== -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/base.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/skeleton.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/layout.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/font-awesome.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/retina.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/animsition.min.css\"/>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- Favicons\r\n");
      out.write("\t================================================== -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"apple-touch-icon-72x72.png\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"apple-touch-icon-114x114.png\">\r\n");
      out.write("\t\r\n");
      out.write("<style>\r\n");
      out.write("#section2{\r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script\r\n");
      out.write("\t\tsrc=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyDDN_ZeJEqk0GSwGVnifo3i_evVo_V5UHk&callback=initMap\"\r\n");
      out.write("\t\tasync defer></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar map;\r\n");
      out.write("\t\tfunction initialize() {\r\n");
      out.write("\t\t\tvar myLatlng = new google.maps.LatLng(37,\r\n");
      out.write("\t\t\t\t\t128);\r\n");
      out.write("\t\t\tvar myOptions = {\r\n");
      out.write("\t\t\t\tzoom : 3,\r\n");
      out.write("\t\t\t\tcenter : myLatlng,\r\n");
      out.write("\t\t\t\tmapTypeId : google.maps.MapTypeId.ROADMAP\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tmap = new google.maps.Map(document.getElementById(\"map_canvas\"),\r\n");
      out.write("\t\t\t\t\tmyOptions);\r\n");
      out.write("\t\t\tvar japanLatlng = new google.maps.LatLng(37,139);\r\n");
      out.write("\t\t\tvar chinaLatlng = new google.maps.LatLng(35,104);\r\n");
      out.write("\t\t\tvar usaLatlng = new google.maps.LatLng(40,-101);\r\n");
      out.write("\t\t\tvar franchLatlng = new google.maps.LatLng(47,2);\r\n");
      out.write("\t\t\tvar vetnamLatlng = new google.maps.LatLng(15,108);\r\n");
      out.write("\t\t\tvar ukLatlng = new google.maps.LatLng(56,-3);\r\n");
      out.write("\t\t\tplaceMarker(myLatlng);\r\n");
      out.write("\t\t\tplaceMarker(japanLatlng);\r\n");
      out.write("\t\t\tplaceMarker(chinaLatlng);\r\n");
      out.write("\t\t\tplaceMarker(usaLatlng);\r\n");
      out.write("\t\t\tplaceMarker(franchLatlng);\r\n");
      out.write("\t\t\tplaceMarker(vetnamLatlng);\r\n");
      out.write("\t\t\tplaceMarker(ukLatlng);\r\n");
      out.write("\r\n");
      out.write("\t\t} // function initialize() 함수 끝\r\n");
      out.write("\r\n");
      out.write("\t\t// 마커 생성 합수\r\n");
      out.write("\t\tfunction placeMarker(location) {\r\n");
      out.write("\t\t\tvar clickedLocation = new google.maps.LatLng(location);\r\n");
      out.write("\t\t\tvar marker = new google.maps.Marker({\r\n");
      out.write("\t\t\t\tposition : location,\r\n");
      out.write("\t\t\t\tanimation: google.maps.Animation.DROP,\r\n");
      out.write("\t\t\t\tmap : map\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tmap.setCenter(location);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* function toggleBounce() {\r\n");
      out.write("\t\t\t\t  if (marker.getAnimation() !== null) {\r\n");
      out.write("\t\t\t\t    marker.setAnimation(null);\r\n");
      out.write("\t\t\t\t  } else {\r\n");
      out.write("\t\t\t\t    marker.setAnimation(google.maps.Animation.BOUNCE);\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\tmarker.addListener('click', toggleBounce); */\r\n");
      out.write("\t\t\tgoogle.maps.event.addListener(marker, 'click', function(event) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tmarker.setAnimation(google.maps.Animation.BOUNCE);\r\n");
      out.write("\t\t\t\tvar lat=marker.position.lat();\r\n");
      out.write("\t\t\t\tvar lng=marker.position.lng();\r\n");
      out.write("\t\t\t\tmarker.setAnimation(null);\r\n");
      out.write("\t\t\t\t$('#worldh').val(lat+\",\"+lng);\r\n");
      out.write("\t\t\t\tconsole.log($('#worldh').val());\r\n");
      out.write("\t\t\t\t\t\tjQuery.ajax({\r\n");
      out.write("\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\tlat : lat,\r\n");
      out.write("\t\t\t\t\t\t\t\tlng : lng\r\n");
      out.write("\t\t\t\t\t\t\t}, \r\n");
      out.write("\t\t\t\t\t\t\turl : \"aboutbest.do\",\r\n");
      out.write("\t\t\t\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t               console.log(\"data : \" + data);\r\n");
      out.write("\t\t\t\t\t               //리턴된 하나의 객체를 문자열로 변환함\r\n");
      out.write("\t\t\t\t\t               var jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\t\t\t               //변한된 문자열을 json 객체로 바꿈\r\n");
      out.write("\t\t\t\t\t               var json = JSON.parse(jsonStr);\r\n");
      out.write("\t\t\t\t\t               var cnt=1;\r\n");
      out.write("\t\t\t\t\t               for(var i in json.list){\r\n");
      out.write("\t\t\t\t\t            \t  var str =\"#aboutImg\";\r\n");
      out.write("\t\t\t\t\t            \t  var strdiv =\"#aboutDiv\";\r\n");
      out.write("\t\t\t\t\t            \t  var strdivv =\"#aboutDivv\";\r\n");
      out.write("\t\t\t\t\t            \t  var lstr=str+cnt;\r\n");
      out.write("\t\t\t\t\t            \t  var lstrdiv=strdiv+cnt;\r\n");
      out.write("\t\t\t\t\t            \t  var lstrdivv=strdivv+cnt; \r\n");
      out.write("\t\t\t\t\t            \t  \r\n");
      out.write("\t\t\t\t\t            \t  $(lstrdivv).html('<h6>'+decodeURIComponent(json.list[i].food_title,\"UTF-8\")+'</h6><p><span>'+decodeURIComponent(json.list[i].food_nation1,\"UTF-8\")+'/'+decodeURIComponent(json.list[i].food_nation2,\"UTF-8\")+'</span></p><ul class=\"skills-list\">'+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t'<li><p><span>&#xf1db;</span>'+decodeURIComponent(json.list[i].food_writer,\"UTF-8\")+'</p></li><li><p><span>&#xf1db;</span>Interaction Design</p>'+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t'</li><li><p><span>&#xf1db;</span>Product Design</p></li><li><p><span>&#xf1db;</span>Website Design</p></li>'+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'</ul><div class=\"social-team\"><ul class=\"list-social-team\"></ul></div>');\r\n");
      out.write("\t\t\t\t\t            \t  $(lstr).attr('src','/finalPro/images/'+json.list[i].food_original_filename);\r\n");
      out.write("\t\t\t\t\t            \t  $(lstr).attr('style',\t'width:290px;height:290px');\r\n");
      out.write("\t\t\t\t\t            \t  var titile=decodeURIComponent(json.list[i].food_title).substring(1,3);\r\n");
      out.write("\t\t\t\t\t            \t  console.log(titile);\r\n");
      out.write("\t\t\t\t\t            \t  if(titile ==\"호텔\"){\r\n");
      out.write("\t\t\t\t\t            \t\t  $(lstrdiv).attr('onclick','location.href=\"hotelpage.do?no='+json.list[i].food_no+'\"');\r\n");
      out.write("\t\t\t\t\t            \t  }else if(titile ==\"음식\"){\r\n");
      out.write("\t\t\t\t\t            \t\t  $(lstrdiv).attr('onclick','location.href=\"foodpage.do?no='+json.list[i].food_no+'\"');\r\n");
      out.write("\t\t\t\t\t            \t  }else if(titile ==\"장소\"){\r\n");
      out.write("\t\t\t\t\t            \t\t  $(lstrdiv).attr('onclick','location.href=\"spotpage.do?no='+json.list[i].food_no+'\"');\r\n");
      out.write("\t\t\t\t\t            \t  }\r\n");
      out.write("\t\t\t\t\t            \t  \r\n");
      out.write("\t\t\t\t\t            \t  \r\n");
      out.write("\t\t\t\t\t            \t  cnt+=1;\r\n");
      out.write("\t\t\t\t\t               }\r\n");
      out.write("\t\t\t\t\t               $('#section2').attr('style','display:block');\r\n");
      out.write("\t\t\t\t\t               document.getElementById(\"aboutfocus\").scrollIntoView(); \r\n");
      out.write("\t\t\t\t\t               \r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tmarker.setMap(map);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"initialize()\">\t\r\n");
      out.write("<div class=\"animsition\">\r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<!-- Primary Page Layout\r\n");
      out.write("\t================================================== -->\r\n");
      out.write("\t\r\n");
      out.write("\t<section class=\"cd-section\">\r\n");
      out.write("\t\t\t<br><br><br><br><br><br><br><br>\r\n");
      out.write("\t\t\t<h4>원하시는 지역을 클릭해주세요</h4><br>\r\n");
      out.write("\t\t\t<div id=\"map_canvas\" style=\"width:100%;height:1000px\">\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</section> <!-- .cd-section --> \r\n");
      out.write("\t\r\n");
      out.write("\t<br><br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("\t<section class=\"section white-background padding-bottom hidden-sec\" id=\"section2\">\r\n");
      out.write("\t\t<div class=\"container\" id=\"aboutfocus\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"worldh\">\r\n");
      out.write("\t\t\t\t<div class=\"four columns\">\t\r\n");
      out.write("\t\t\t\t\t<div class=\"team-wrap\" id=\"aboutDiv1\">\t\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/team1.jpg\" alt=\"\" id=\"aboutImg1\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask-team\" id=\"aboutDivv1\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"four columns\">\t\r\n");
      out.write("\t\t\t\t\t<div class=\"team-wrap\" id=\"aboutDiv2\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/team2.jpg\" alt=\"\" id=\"aboutImg2\">\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask-team\" id=\"aboutDivv2\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t<div class=\"four columns\">\t\r\n");
      out.write("\t\t\t\t\t<div class=\"team-wrap\" id=\"aboutDiv3\">\t\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/team3.jpg\" alt=\"\" id=\"aboutImg3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask-team\" id=\"aboutDivv3\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"four columns\">\t\r\n");
      out.write("\t\t\t\t\t<div class=\"team-wrap\" id=\"aboutDiv4\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/team4.jpg\" alt=\"\" id=\"aboutImg4\">\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask-team\" id=\"aboutDivv4\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- JAVASCRIPT\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\t\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/modernizr.custom.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.animsition.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("(function($) { \"use strict\";\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t  \r\n");
      out.write("\t  $(\".animsition\").animsition({\r\n");
      out.write("\t  \r\n");
      out.write("\t\tinClass               :   'zoom-in-sm',\r\n");
      out.write("\t\toutClass              :   'zoom-out-sm',\r\n");
      out.write("\t\tinDuration            :    800,\r\n");
      out.write("\t\toutDuration           :    800,\r\n");
      out.write("\t\tlinkElement           :   '.animsition-link', \r\n");
      out.write("\t\t// e.g. linkElement   :   'a:not([target=\"_blank\"]):not([href^=#])'\r\n");
      out.write("\t\tloading               :    true,\r\n");
      out.write("\t\tloadingParentElement  :   'body', //animsition wrapper element\r\n");
      out.write("\t\tloadingClass          :   'animsition-loading',\r\n");
      out.write("\t\tunSupportCss          : [ 'animation-duration',\r\n");
      out.write("\t\t\t\t\t\t\t\t  '-webkit-animation-duration',\r\n");
      out.write("\t\t\t\t\t\t\t\t  '-o-animation-duration'\r\n");
      out.write("\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t//\"unSupportCss\" option allows you to disable the \"animsition\" in case the css property in the array is not supported by your browser. \r\n");
      out.write("\t\t//The default setting is to disable the \"animsition\" in a browser that does not support \"animation-duration\".\r\n");
      out.write("\t\t\r\n");
      out.write("\t\toverlay               :   false,\r\n");
      out.write("\t\t\r\n");
      out.write("\t\toverlayClass          :   'animsition-overlay-slide',\r\n");
      out.write("\t\toverlayParentElement  :   'body'\r\n");
      out.write("\t  });\r\n");
      out.write("\t});  \r\n");
      out.write("})(jQuery);\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/retina-1.1.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/classie.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cbpAnimatedHeader.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/menu.js\"></script> \t\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/scroll.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/custom-about.js\"></script>  \t  \r\n");
      out.write("<!-- End Document\r\n");
      out.write("================================================== -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /about.jsp(160,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("header.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /about.jsp(209,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
