/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2018-04-16 06:08:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1520406738000L));
    _jspx_dependants.put("jar:file:/C:/finalProject5/finalProject2/finalPro/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/base.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/skeleton.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layout.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/retina.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animsition.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animsition.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animsition.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"72x72\"\r\n");
      out.write("\thref=\"apple-touch-icon-72x72.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"114x114\"\r\n");
      out.write("\thref=\"apple-touch-icon-114x114.png\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".title {\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title.hover {\r\n");
      out.write("\tcolor: orange;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".headimg {\r\n");
      out.write("\twidth: 40px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".headimg2 {\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".arrow_box {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tpadding: 16px;\r\n");
      out.write("\t-webkit-border-radius: 8px;\r\n");
      out.write("\t-moz-border-radius: 8px;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("\tbackground: #333;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\twidth: 90px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".arrow_box:after {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tbottom: 100%;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\twidth: 0;\r\n");
      out.write("\theight: 0;\r\n");
      out.write("\tmargin-left: -40px;\r\n");
      out.write("\tborder: solid transparent;\r\n");
      out.write("\tborder-color: rgba(51, 51, 51, 0);\r\n");
      out.write("\tborder-bottom-color: #333;\r\n");
      out.write("\tborder-width: 10px;\r\n");
      out.write("\tpointer-events: none;\r\n");
      out.write("\tcontent: \" \";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hspan:hover+p.arrow_box {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"bootstrap-3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- <script>\r\n");
      out.write("     $(document).ready(function() {  \r\n");
      out.write("      \r\n");
      out.write("         console.log(\"아작\");\r\n");
      out.write("         var id1 = document.getElementById(\"loginU2\").value;\r\n");
      out.write("         console.log(id1);\r\n");
      out.write("         jQuery.ajax({\r\n");
      out.write("            type : \"post\",\r\n");
      out.write("            data : {LoginId:id1},\r\n");
      out.write("            url : \"headermsg.do\",\r\n");
      out.write("            success: function(data){\r\n");
      out.write("               if(data==\"ok\"){\r\n");
      out.write("                  console.log(\"아작~\");\r\n");
      out.write("                  var rs=$('#msgdiv').html();\r\n");
      out.write("                  rs+=\"<img src='/finalPro/img/newimg2.png' class='hnewimg'/>\";\r\n");
      out.write("                  $('#msgdiv').html(rs);\r\n");
      out.write("               }\r\n");
      out.write("            },\r\n");
      out.write("            error: function(request, status, errorData){\r\n");
      out.write("               alert(\"error code : \" + request.status + \"\\n\"\r\n");
      out.write("                  + \"message : \" + request.responseText + \"\\n\"\r\n");
      out.write("                  + \"error : \" + errorData);\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("      \r\n");
      out.write("         \r\n");
      out.write("    \r\n");
      out.write("    });\r\n");
      out.write("</script> -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$\r\n");
      out.write("\t\t\t.ajax({\r\n");
      out.write("\t\t\t\turl : \"nationlist.do\",\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\t\t\t//변환된 문자열을 json 객체로 바꿈\r\n");
      out.write("\t\t\t\t\tvar json = JSON.parse(jsonStr);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar nationHtml = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfor ( var i in json.list) {\r\n");
      out.write("\t\t\t\t\t\tvar sNation = decodeURIComponent(json.list[i].nation1);\r\n");
      out.write("\t\t\t\t\t\tconsole.log(sNation);\r\n");
      out.write("\t\t\t\t\t\tnationHtml += '<li class=\"dropdown\"><a href=\"#\" class=\"animsition-link\">'\r\n");
      out.write("\t\t\t\t\t\t\t+ sNation\r\n");
      out.write("\t\t\t\t\t\t\t+ '　　　　　</a><ul class=\"dropdown-menu dropdown-menu-right\"><li><a href=\"foodlist.do?nation1='\r\n");
      out.write("\t\t\t\t\t\t\t+ sNation\r\n");
      out.write("\t\t\t\t\t\t\t+ '\" class=\"animsition-link\" width=50px>음식점　　　　</a></li><li><a href=\"hotellist.do?nation1='\r\n");
      out.write("\t\t\t\t\t\t\t+ sNation\r\n");
      out.write("\t\t\t\t\t\t\t+ '\" class=\"animsition-link\">숙소　　　　</a></li><li><a href=\"slist.do?nation1='\r\n");
      out.write("\t\t\t\t\t\t\t+ sNation\r\n");
      out.write("\t\t\t\t\t\t\t+ '\" class=\"animsition-link\">관광지　　　　</a></li></ul></li>';\r\n");
      out.write("\t\t\t\t\t/*  '<li class=\"dropdown\"><a href=\"#\" class=\"animsition-link\">'+ sNation　+'　　</a><ul class=\"dropdown-menu dropdown-menu-right\"><li><a href=\"work2.jsp\" class=\"animsition-link\" width=50px>음식점</a></li><li><a href=\"work2.jsp\" class=\"animsition-link\">숙소</a></li><li><a href=\"work2.jsp\" class=\"animsition-link\">관광지</a></li></ul></li>'*/\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#nationName\").html(nationHtml);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- MENU\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"menu-wrap\" class=\"menu-back cbp-af-header\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"sixteen columns\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"about.jsp\" class=\"title\"> <tt style=\"color: red\">T</tt>\r\n");
      out.write("\t\t\t\t\t<tt style=\"color: #E26812\">r</tt>\r\n");
      out.write("\t\t\t\t\t<tt style=\"color: #FDE102\">a</tt> <tt style=\"color: #03A200\">v</tt>\r\n");
      out.write("\t\t\t\t\t<tt style=\"color: #030AF5\">e</tt>\r\n");
      out.write("\t\t\t\t\t<tt style=\"color: #094B6E\">l</tt> <tt style=\"color: #82108D\">S</tt>\r\n");
      out.write("\t\t\t\t\t<tt style=\"color: red\">t</tt>\r\n");
      out.write("\t\t\t\t\t<tt style=\"color: #E26812\">a</tt> <tt style=\"color: #FDE102\">r</tt>\r\n");
      out.write("\t\t\t\t\t<tt style=\"color: #03A200\">g</tt>\r\n");
      out.write("\t\t\t\t\t<tt style=\"color: #030AF5\">r</tt> <tt style=\"color: #094B6E\">a</tt>\r\n");
      out.write("\t\t\t\t\t<tt style=\"color: #82108D\">m</tt>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"slimmenu\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a class=\"active-menu animsition-link\" href=\"about.jsp\">Home</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Nation</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"submenu-back\">\r\n");
      out.write("\t\t\t\t\t\t\t<p id=\"nationName\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">Review</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"submenu-back\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"rlist.do\" class=\"animsition-link\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"loginCheck();\">Review</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"flist.do\" class=\"animsition-link\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"loginCheck();\">Feedback</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\" class=\"animsition-link\">Rootconsulting</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"submenu-back\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"datecheck.do\" class=\"animsition-link\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"loginCheck();\">new root </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"myrootlist.do?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"animsition-link\" onclick=\"loginCheck();\">my root </a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"nlist.do\" class=\"animsition-link\">Notice</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"qlist.do\" class=\"animsition-link\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document)\r\n");
      out.write("\t\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tif ($('#loginU2').val() != null) {\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(\"아작\");\r\n");
      out.write("\t\t\t\t\t\t\t\tvar id1 = document.getElementById(\"loginU2\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(id1);\r\n");
      out.write("\t\t\t\t\t\t\t\tjQuery\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tloginId : id1\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\turl : \"headermsg.do\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tconsole.log(\"아작~\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar rs = $('#msgdiv')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.html();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\trs += '<img src=\"/finalPro/img/newimg2.png\" class=\"hnewimg\"/>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$('#msgdiv').html(rs);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\terror : function(request, status,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\terrorData) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talert(\"error code : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ request.status + \"\\n\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"message : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ request.responseText\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"\\n\" + \"error : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ errorData);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/modernizr.custom.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.animsition.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t(function($) {\r\n");
      out.write("\t\t\t\"use strict\";\r\n");
      out.write("\t\t\t$(document).ready(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$(\".animsition\").animsition(\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinClass : 'zoom-in-sm',\r\n");
      out.write("\t\t\t\t\t\t\t\t\toutClass : 'zoom-out-sm',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinDuration : 800,\r\n");
      out.write("\t\t\t\t\t\t\t\t\toutDuration : 800,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlinkElement : '.animsition-link',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// e.g. linkElement   :   'a:not([target=\"_blank\"]):not([href^=#])'\r\n");
      out.write("\t\t\t\t\t\t\t\t\tloading : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tloadingParentElement : 'body', //animsition wrapper element\r\n");
      out.write("\t\t\t\t\t\t\t\t\tloadingClass : 'animsition-loading',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tunSupportCss : [ 'animation-duration',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t'-webkit-animation-duration',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t'-o-animation-duration' ],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//\"unSupportCss\" option allows you to disable the \"animsition\" in case the css property in the array is not supported by your browser. \r\n");
      out.write("\t\t\t\t\t\t\t\t\t//The default setting is to disable the \"animsition\" in a browser that does not support \"animation-duration\".\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\toverlay : false,\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\toverlayClass : 'animsition-overlay-slide',\r\n");
      out.write("\t\t\t\t\t\t\t\t\toverlayParentElement : 'body'\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t})(jQuery);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("   function loginCheck() {\r\n");
      out.write("      if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.member_id == null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("        alert(\" 로그인하셔야 합니다.\");   \r\n");
      out.write("        document.location.href =\"loginForm.do\";\r\n");
      out.write("      }\r\n");
      out.write("    };  \r\n");
      out.write("  </script> \r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.easing.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/retina-1.1.0.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/classie.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/cbpAnimatedHeader.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/menu.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/scroll.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/animated-headline.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.fs.tipper.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/custom-home1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /header.jsp(161,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<a href=\"enrollForm.do\" style=\"float: right;\"><span\r\n");
          out.write("\t\t\t\t\t\tclass=\"hspan\"><img class=\"headimg\"\r\n");
          out.write("\t\t\t\t\t\t\tsrc=\"/finalPro/img/clipboard.png\" style=\"margin-right: 20px;\"></span>\r\n");
          out.write("\t\t\t\t\t<p class=\"arrow_box\" style=\"margin-top: 10px;\">회원가입</p></a>\r\n");
          out.write("\t\t\t\t\t<a href=\"loginForm.do\" style=\"float: right;\"><span\r\n");
          out.write("\t\t\t\t\t\tclass=\"hspan\"><img class=\"headimg\"\r\n");
          out.write("\t\t\t\t\t\t\tsrc=\"/finalPro/img/left.png\" style=\"margin-right: 20px;\"></span>\r\n");
          out.write("\t\t\t\t\t<p class=\"arrow_box\" style=\"margin-top: 10px;\">로그인</p></a>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /header.jsp(171,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t<h6 style=\"float: right;\">\r\n");
          out.write("\t\t\t\t\t\t<tt style=\"color: #6496F3\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</tt>\r\n");
          out.write("\t\t\t\t\t\t님 환영합니다.\r\n");
          out.write("\t\t\t\t\t</h6>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t\t<a href=\"logout.do\" style=\"float: right;\"><span class=\"hspan\"><img\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"headimg2\" src=\"/finalPro/img/logout.png\"></span>\r\n");
          out.write("\t\t\t\t\t<p class=\"arrow_box\" style=\"margin-top: 10px;\">로그아웃</p></a>\r\n");
          out.write("\t\t\t\t\t<a href=\"mupdateForm.do?member_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"float: right;\"><span class=\"hspan\"><img\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"headimg2\" src=\"/finalPro/img/info.png\"></span>\r\n");
          out.write("\t\t\t\t\t<p class=\"arrow_box\" style=\"margin-top: 10px;\">정보수정</p></a>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t<div style=\"float: right;\" id=\"msgdiv\">\r\n");
          out.write("\t\t\t\t\t\t<!-- <img src=\"/finalPro/img/newimg.png\" class=\"hnewimg\"/>-->\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t<a href=\"block.do\" style=\"float: right;\"><span class=\"hspan\"><img\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"headimg\" src=\"/finalPro/img/police.png\"\r\n");
          out.write("\t\t\t\t\t\t\tstyle=\"margin-top: -10px;\"></span>\r\n");
          out.write("\t\t\t\t\t\t<p class=\"arrow_box\" style=\"margin-top: 10px;\">신고하기</p></a>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /header.jsp(191,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_id eq 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<a href=\"admin.do?currentPage=1\" style=\"float: right;\"><span\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"hspan\"><img class=\"headimg\"\r\n");
          out.write("\t\t\t\t\t\t\t\tsrc=\"/finalPro/img/card.png\"></span>\r\n");
          out.write("\t\t\t\t\t\t\t<p class=\"arrow_box\">회원 관리</p></a>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /header.jsp(200,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<a href=\"msg.do?loginId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><span\r\n");
          out.write("\t\t\t\t\t\t\t\tclass=\"hspan\"><img class=\"headimg\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tsrc=\"/finalPro/img/open.png\"></span>\r\n");
          out.write("\t\t\t\t\t\t\t\t<p class=\"arrow_box\">쪽지함</p></a>\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"loginU2\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
