/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2018-01-31 17:26:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.best;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vrBoard.model.vo.vrBoard;
import likePlace.model.vo.likePlace;
import java.util.*;
import member.model.vo.Member;

public final class best_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/best/../../header.jsp", Long.valueOf(1517397470805L));
    _jspx_dependants.put("/views/best/../../footer.jsp", Long.valueOf(1517224153540L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("likePlace.model.vo.likePlace");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("vrBoard.model.vo.vrBoard");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	likePlace like = (likePlace) request.getAttribute("info");

      out.write('\r');
      out.write('\n');
 
	ArrayList<vrBoard> list = (ArrayList<vrBoard>)request.getAttribute("list");
	 int listCount = ((Integer)request.getAttribute("listCount")).intValue();
	   int currentPage = ((Integer)request.getAttribute("currentPage")).intValue();
	   int startPage = ((Integer)request.getAttribute("startPage")).intValue();
	   int endPage = ((Integer)request.getAttribute("endPage")).intValue();
	   int maxPage = ((Integer)request.getAttribute("maxPage")).intValue();

      out.write('\r');
      out.write('\n');
 
	ArrayList<likePlace> likelist = (ArrayList<likePlace>)request.getAttribute("likelist"); 
	boolean flag = false;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("button#btn11 {\r\n");
      out.write("\tborder: 1px solid skyblue;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground: lightgray;\r\n");
      out.write("\tborder-radius: 12px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button#btn11:hover {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground-color: #0069d9;\r\n");
      out.write("\tborder-radius: 12px;\r\n");
      out.write("\tborder-color: #0062cc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button#btn11:focus, button#btn11.focus {\r\n");
      out.write("\tbox-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.5);\r\n");
      out.write("\tborder-radius: 12px;\r\n");
      out.write("\tbackground-color: #0069d9;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>BEST</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction imgclick() {\r\n");
      out.write("\t\tvar img = document.getElementById('image');\r\n");
      out.write("\r\n");
      out.write("\t\tif (img.src.match(\"like_no\")) {\r\n");
      out.write("\t\t\timg.src = \"/semi/images/like_yes.png\";\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\timg.src = \"/semi/images/like_no.png\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navigation -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");

	Member member = (Member)session.getAttribute("member");

      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(" table{\r\n");
      out.write("    border-collapse: separate;\r\n");
      out.write("   border-spacing:0px 4px\r\n");
      out.write(" }\r\n");
      out.write(" .modal-dialog{\r\n");
      out.write("      width:450px;\r\n");
      out.write("      height:350px;\r\n");
      out.write(" }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav\r\n");
      out.write("\t\tclass=\"navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"intro.jsp\">WhybiS</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler navbar-toggler-right\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbarResponsive\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarResponsive\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/intro.jsp\">HOME</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/vrimg\">PLACE</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/views/best/best.jsp\">BEST</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/rblist?page=1\"> BOARD </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/qlist?page=1\"> Q&A </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"\" id=\"navbarDropdownBlog\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\tMY PAGE </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"navbarDropdownBlog\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"full-width.html\">내 정보 보기 및 수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"sidebar.html\">나의 관심 장소 보기</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"faq.html\">내가 쓴 글 보기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<li></li>\r\n");
      out.write("\t\t\t\t\t\t<li></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");
 if(member == null){  //로그인하지 않았다면 
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"modal\" data-target=\"#myModal\"> LOGIN </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"views/member/memberEnroll.jsp\"> JOIN </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<tr><td>");
      out.print( member.getSmemberName() );
      out.write(" 님 &nbsp;&nbsp;</td>\r\n");
      out.write("\t   <td><a href=\"/semi/logout\">로그아웃</a></td></tr>\r\n");
      out.write("\t   <tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t");
 if(member.getSmemberId().equals("admin01")){ 
      out.write(" \r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;<a href=\"/semi/mlist\">회원 정보 전체보기</a> ");
 }
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("         aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("         <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("               <div class=\"modal-header\">\r\n");
      out.write("               <h4 class=\"modal-title\" id=\"myModalLabel\">로그인</h4>\r\n");
      out.write("                  <button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("                     <span aria-hidden=\"true\">×</span><span class=\"sr-only\">Close</span>\r\n");
      out.write("                  </button>\r\n");
      out.write("                  \r\n");
      out.write("               </div>\r\n");
      out.write("         <!--모달 바디-->\r\n");
      out.write("          <form action=\"login\" method =\"post\">\r\n");
      out.write("               <div class=\"modal-body\">\r\n");
      out.write("               \r\n");
      out.write("                  <table width=\"250\" cellpadding=\"0\" cellspacing=\"0\"  align = \"center\">\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>아이디</td>\r\n");
      out.write("                        <td><input type=\"text\" name=\"userid\"></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     \r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>암     호</td>\r\n");
      out.write("                        <td><input type=\"password\" name=\"userpwd\"></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr align = \"center\">\r\n");
      out.write("                        <td colspan=\"2\"><a href=\"#\">아이디/암호 찾기</a></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr align = \"center\">\r\n");
      out.write("                     <td colspan=\"2\"><a href=\"#\">회원가입</a></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"modal-footer\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                 \r\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("                  </form>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!--    <script src=\"http://googledrive.com/host/0B-QKv6rUoIcGREtrRTljTlQ3OTg\"></script>\r\n");
      out.write("   ie10-viewport-bug-workaround.js\r\n");
      out.write("   <script src=\"http://googledrive.com/host/0B-QKv6rUoIcGeHd6VV9JczlHUjg\"></script> -->\r\n");
      out.write("   <!-- holder.js -->\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page Content -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Page Heading -->\r\n");
      out.write("\t\t<h1 class=\"my-4\">\r\n");
      out.write("\t\t\tBEST <small>인기</small>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t<div align=\"center\" width=\"80%\">\r\n");
      out.write("\t\t\t<button id=\"btn11\"\r\n");
      out.write("\t\t\t\tonclick=\"location.href='/semi/bestplace?page=");
      out.print(currentPage);
      out.write("&userId=");
      out.print(member.getSmemberId());
      out.write("'\">장소</button>\r\n");
      out.write("\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<button id=\"btn11\" onclick=\"location='/semi/views/best/bestRes.jsp'\">편의시설</button>\r\n");
      out.write("\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<button id=\"btn11\"\r\n");
      out.write("\t\t\t\tonclick=\"location='/semi/views/best/bestHotel.jsp'\">숙소</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Project One -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
if(!likelist.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t");
 for(vrBoard r : list){ 
      out.write("\r\n");
      out.write("\t\t\t\t");
for(likePlace l : likelist) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(flag==false){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(r.getVrboardnum() == l.getLikePlaceNum()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"> <img class=\"img-fluid rounded mb-3 mb-md-0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"http://placehold.it/700x300\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>");
      out.print(r.getVrboardtitle() );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"/semi/vrunlike\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"image\" type=\"image\" src=\"/semi/images/like_yes.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"imgclick()\"> <input type=\"hidden\" name=\"userId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=");
      out.print(member.getSmemberId());
      out.write("> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"placeNum\" value=");
      out.print(r.getVrboardnum());
      out.write("> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"hidden\" name=\"placeNum\" value=3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"page\" value=");
      out.print(currentPage );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<p>");
      out.print(r.getVrboardcontent() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-primary\" href=\"#\">View Project</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
 flag=true; } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img class=\"img-fluid rounded mb-3 mb-md-0\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"http://placehold.it/700x300\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t\t\t<h3>");
      out.print(r.getVrboardtitle() );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<form action=\"/semi/vrlike\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"image\" type=\"image\" src=\"/semi/images/like_no.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"imgclick()\"> <input type=\"hidden\" name=\"userId\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=");
      out.print(member.getSmemberId());
      out.write("> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"placeNum\" value=");
      out.print(r.getVrboardnum());
      out.write("> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"hidden\" name=\"placeNum\" value=3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"page\" value=");
      out.print(currentPage );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<p>");
      out.print(r.getVrboardcontent() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-primary\" href=\"#\">View Project</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
  /* flag=true; */ } } 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t");
  } flag=false;  
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t");
 for(vrBoard r : list){ 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"> <img class=\"img-fluid rounded mb-3 mb-md-0\"\r\n");
      out.write("\t\t\t\t\tsrc=\"http://placehold.it/700x300\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t<h3>");
      out.print(r.getVrboardtitle() );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t<form action=\"/semi/vrlike\">\r\n");
      out.write("\t\t\t\t\t<input id=\"image\" type=\"image\" src=\"/semi/images/like_no.png\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"imgclick()\"> <input type=\"hidden\" name=\"userId\"\r\n");
      out.write("\t\t\t\t\t\tvalue=");
      out.print(member.getSmemberId());
      out.write("> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\tname=\"placeNum\" value=");
      out.print(r.getVrboardnum());
      out.write("> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"hidden\" name=\"placeNum\" value=3>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"page\" value=");
      out.print(currentPage );
      out.write(">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t<p>");
      out.print(r.getVrboardcontent() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-primary\" href=\"#\">View Project</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<ul class=\"pagination justify-content-center\">\r\n");
      out.write("\t\t\t");

				if (currentPage <= 1) {
			
      out.write("\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"/semi/vrlist?page=1\"\r\n");
      out.write("\t\t\t\taria-label=\"Previous\"> <span aria-hidden=\"true\">&laquo;</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"/semi/vrlist?page=");
      out.print(currentPage - 1);
      out.write("\"\r\n");
      out.write("\t\t\t\taria-label=\"Previous\"> <span aria-hidden=\"true\">&laquo;</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");

				for (int p = startPage; p <= endPage; p++) {
					if (p == currentPage) {
			
      out.write("<li class=\"page-item\"><a class=\"page-link\" >");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"/semi/vrlist?page=");
      out.print(p);
      out.write('"');
      out.write('>');
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t");

				}
				}
			
      out.write("\r\n");
      out.write("\t\t\t");

				if (currentPage >= maxPage) {
			
      out.write("\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"page-item\"><a class=\"page-link\" href=\"/semi/vrlist?page=");
      out.print(currentPage + 1);
      out.write("\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Next\"> <span aria-hidden=\"true\">&raquo;</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"page-item\"><a class=\"page-link\" href=\"/semi/vrlist?page=");
      out.print(endPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Next\"> <span aria-hidden=\"true\">&raquo;</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Bootstrap core JavaScript -->\r\n");
      out.write("\t<script src=\"jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"jqueryintro/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"jquery/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"jquery/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"jquery/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("   <script src=\"jqueryintro/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer class=\"py-5 bg-dark\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<p class=\"m-0 text-center text-white\">Copyright &copy; Your\r\n");
      out.write("\t\t\t\tWebsite 2018</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container -->\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
